// Refresh the engine-runtime pins from packaging/runtime.lock.json:
//   - python-build-standalone sha256 per target (from the release's SHA256SUMS)
//   - packaging/requirements/<target>.txt  (uv pip compile --generate-hashes, cross-platform, from the pinned
//     video-studio commit's requirements.txt + per-target extras)
//   - packaging/ffmpeg/<target>.txt        (conda explicit list with sha256 for the LGPL ffmpeg build)
// Needs: uv on PATH (https://docs.astral.sh/uv/), network. Run after changing versions or the vstudio commit:
//   node scripts/runtime/lock.mjs [--only=requirements|ffmpeg|python]
import fs from 'node:fs';
import path from 'node:path';
import { arg, log, micromamba, readLock, ROOT, run, writeLock, CACHE } from './common.mjs';

const lock = readLock();
const only = arg('only');
const targets = Object.keys(lock.targets);

async function lockPython() {
  const { release, version, flavor } = lock.python;
  const sums = await (await fetch(`https://github.com/astral-sh/python-build-standalone/releases/download/${release}/SHA256SUMS`)).text();
  for (const t of targets) {
    const name = `cpython-${version}+${release}-${lock.targets[t].pbs}-${flavor}.tar.gz`;
    const line = sums.split('\n').find((l) => l.endsWith(`  ${name}`));
    if (!line) throw new Error(`no SHA256SUMS entry for ${name}`);
    lock.python.sha256[t] = line.split(' ')[0];
  }
  writeLock(lock);
  log('python sha256 updated');
}

async function lockRequirements() {
  const raw = `https://raw.githubusercontent.com/zyziyun/video-studio/${lock.vstudio.commit}/requirements.txt`;
  const res = await fetch(raw);
  if (!res.ok) throw new Error(`GET ${raw}: ${res.status} (is the commit pushed?)`);
  const base = (await res.text()).split('\n').map((l) => l.trim()).filter((l) => l && !l.startsWith('#'));
  const dir = path.join(ROOT, 'packaging', 'requirements');
  fs.mkdirSync(dir, { recursive: true });
  const overrides = path.join(dir, 'overrides.txt');
  fs.writeFileSync(overrides, lock.pip.overrides.join('\n') + '\n');
  for (const t of targets) {
    const extra = lock.pip.extra[t] ?? [];
    // an extra that names a base package (e.g. mediapipe==x) replaces the base line
    const names = new Set(extra.map((e) => e.split(/[<>=!~ ;[]/)[0].toLowerCase()));
    const lines = [...base.filter((b) => !names.has(b.split(/[<>=!~ ;[]/)[0].toLowerCase())), ...extra];
    const inFile = path.join(dir, `${t}.in`);
    fs.writeFileSync(inFile, `# generated by scripts/runtime/lock.mjs from video-studio@${lock.vstudio.commit.slice(0, 12)}\n${lines.join('\n')}\n`);
    const env = { ...process.env };
    if (lock.targets[t].macosMin) env.MACOSX_DEPLOYMENT_TARGET = lock.targets[t].macosMin;
    run('uv', ['pip', 'compile', inFile, '--python-version', lock.python.version.split('.').slice(0, 2).join('.'),
      '--python-platform', lock.targets[t].uvPlatform, '--generate-hashes', '--override', overrides,
      '--no-header', '--quiet', '--output-file', path.join(dir, `${t}.txt`)], { env });
  }
}

async function lockFfmpeg() {
  const mm = await micromamba(lock);
  const dir = path.join(ROOT, 'packaging', 'ffmpeg');
  fs.mkdirSync(dir, { recursive: true });
  for (const t of targets) {
    const out = run(mm, ['create', '--yes', '--dry-run', '--json', '--prefix', path.join(CACHE, 'dry'), '--platform', lock.targets[t].conda,
      '-c', lock.ffmpeg.channel, '--override-channels', lock.ffmpeg.spec],
    { capture: true, env: { ...process.env, MAMBA_ROOT_PREFIX: path.join(CACHE, 'mamba') } });
    const pkgs = JSON.parse(out).actions.LINK.sort((a, b) => a.name.localeCompare(b.name));
    const lines = [
      `# conda explicit lock for ${t}: ${lock.ffmpeg.spec} (generated by scripts/runtime/lock.mjs)`,
      ...pkgs.map((p) => `# ${p.name} ${p.version} ${p.build_string} | ${p.license ?? '?'}`),
      '@EXPLICIT',
      ...pkgs.map((p) => `${p.url}#${p.md5}`),
    ];
    fs.writeFileSync(path.join(dir, `${t}.txt`), lines.join('\n') + '\n');
    fs.writeFileSync(path.join(dir, `${t}.json`), JSON.stringify(pkgs.map((p) => ({ name: p.name, version: p.version, build: p.build_string, license: p.license, url: p.url, sha256: p.sha256 })), null, 1) + '\n');
    log(`ffmpeg ${t}: ${pkgs.length} packages`);
  }
}

if (!only || only === 'python') await lockPython();
if (!only || only === 'requirements') await lockRequirements();
if (!only || only === 'ffmpeg') await lockFfmpeg();
