// Use-case landing pages (SEO long tail, IMPLEMENTATION.md §6.9). One entry per page, written per language
// (not machine-translated). Only claims the engine actually supports (README "What the engine covers").
import type { Lang } from '../i18n';
import type { ImgKey } from '../lib/images';

export const USE_CASES = ['podcast-clips', 'interview-clips', 'course-slicing', 'talking-head', 'studios'] as const;
export type UseCaseSlug = (typeof USE_CASES)[number];

interface Item { t: string; b: string }
export interface UseCase {
  nav: string; title: string; description: string;
  kicker: string; h1: string; intro: string;
  img: ImgKey; figCaption: string; figAlt: string;
  pointsT: string; points: Item[];
  stepsT: string; steps: Item[];
  note?: Item;
  faq: { q: string; a: string }[];
  cta: string;
  /** two sibling pages + one comparison, for internal links */
  related: string[];
}

const DATA: Record<UseCaseSlug, Record<Lang, UseCase>> = {
  // ------------------------------------------------------------------ podcast
  'podcast-clips': {
    en: {
      nav: 'Podcast clips',
      title: 'Podcast to shorts: clip a whole episode at once | Reelfold',
      description: 'Turn a video podcast into vertical clips for TikTok, Reels, Shorts, Xiaohongshu and Douyin. Free, open-source Mac app; AI picks the moments, you review only what’s flagged.',
      kicker: 'Use case · Podcasts',
      h1: 'Podcast clips, cut from the whole episode.',
      intro: 'Drop in a video podcast and say how many clips you want and where they go. Reelfold reads the transcript, picks the answers that stand on their own, and renders each one for every platform you named, with captions, a cover and post copy.',
      img: 'talkinghead', figCaption: 'Vertical clips with captions and a notes panel, rendered on a Mac.', figAlt: 'A contact sheet of vertical clips of the creator speaking, each with burned-in captions and a short notes panel.',
      pointsT: 'What you get from one episode',
      points: [
        { t: 'Moments that stand alone', b: 'The plan lists each clip with its start and end, a title and why it was picked. Change a line before anything renders.' },
        { t: 'Captions placed per app', b: 'Captions sit inside each platform’s safe area, so they aren’t hidden under TikTok’s or Xiaohongshu’s buttons.' },
        { t: 'Tidy speech, your call', b: 'Pauses, filler words and restarts are suggested as cuts. Clear ones are applied; the rest wait for a yes from you.' },
        { t: 'One folder per platform', b: 'Every clip comes out in each format you asked for, with a cover, loudness set and copy within each platform’s limits.' },
      ],
      stepsT: 'From episode to a week of clips',
      steps: [
        { t: 'Describe the batch', b: '“Ten clips from this episode, about a minute each, for Shorts, Reels and Xiaohongshu.”' },
        { t: 'Approve the plan', b: 'Read the picks and the AI cost estimate. Swap a moment, shorten one, or approve all.' },
        { t: 'Let it run', b: 'Cutting, captions, covers and exports run on your Mac, several clips at a time.' },
        { t: 'Check the flagged few', b: 'Automatic checks catch missing caption words, loudness and length. You look only at those.' },
      ],
      faq: [
        { q: 'Does it work with audio-only podcasts?', a: 'Reelfold is built for video. For an audio-only show you need a video track first, such as a still image or a recorded camera feed.' },
        { q: 'How long can the episode be?', a: 'Long recordings are the point. The batch on our home page started from a 72-minute recording and produced 24 clips.' },
        { q: 'Can it handle two speakers?', a: 'Yes. Clips can use a vertical, side-by-side or landscape layout, and faces or name labels can be masked if a guest wants that.' },
      ],
      cta: 'Clip your next episode on your own Mac.',
      related: ['interview-clips', 'talking-head', 'compare/opus-clip'],
    },
    zh: {
      nav: '播客切片',
      title: '播客切片：一整期播客，一次剪成多条短视频 | 千剪',
      description: '把视频播客剪成小红书、抖音、视频号、Shorts、Reels 的竖屏短片。免费开源的 Mac 应用，AI 挑片段，你只看被标出来的几条。',
      kicker: '场景 · 播客',
      h1: '一整期播客，一次切成多条。',
      intro: '拖进一期视频播客，说清要几条、发哪些平台。千剪读文字稿，挑出能单独成立的回答，按你点名的每个平台各渲染一版，字幕、封面和文案都配好。',
      img: 'talkinghead', figCaption: '带字幕和笔记面板的竖屏片段，在 Mac 上渲染。', figAlt: '一组竖屏片段的缩略图：创作者本人出镜，每条都有烧录字幕和简短的笔记面板。',
      pointsT: '一期节目能拿到什么',
      points: [
        { t: '能单独成立的片段', b: '计划里列出每条的起止时间、标题和选它的理由。渲染之前，改哪一行都行。' },
        { t: '字幕按平台摆放', b: '字幕放在各平台的安全区内，不会被抖音、小红书的按钮挡住。' },
        { t: '去气口，由你拍板', b: '停顿、口头禅、说错重来都会列成建议。把握大的直接剪，拿不准的等你确认。' },
        { t: '每个平台一个文件夹', b: '每条片段按你要的尺寸各出一版，封面、响度、文案字数都按平台规矩来。' },
      ],
      stepsT: '从一期节目到一周的片段',
      steps: [
        { t: '描述这一批', b: '“这期剪十条，每条一分钟左右，发 Shorts、Reels 和小红书。”' },
        { t: '确认计划', b: '看一遍选段和 AI 费用预估。换一段、剪短一段，或者全部确认。' },
        { t: '交给它跑', b: '剪辑、字幕、封面、导出都在你的 Mac 上进行，几条同时跑。' },
        { t: '只看被标出来的', b: '自动检查会抓出字幕漏字、响度和时长问题。你只看这几条。' },
      ],
      faq: [
        { q: '纯音频播客能用吗？', a: '千剪是为视频做的。纯音频节目需要先有一条视频轨，比如一张静态图，或者录下来的机位画面。' },
        { q: '节目可以多长？', a: '长录像正是它的用处。首页那一批，就是从一条 72 分钟的录像剪出了 24 条。' },
        { q: '两个人对谈可以吗？', a: '可以。片段可以用竖屏、左右并排或横屏布局；嘉宾不想露脸时，可以遮住人脸或模糊姓名条。' },
      ],
      cta: '下一期节目，在你自己的 Mac 上切。',
      related: ['interview-clips', 'talking-head', 'compare/opus-clip'],
    },
    fr: {
      nav: 'Clips de podcast',
      title: 'Podcast en clips courts : tout un épisode d’un coup | Reelfold',
      description: 'Transformez un podcast vidéo en clips verticaux pour TikTok, Reels, Shorts, Xiaohongshu et Douyin. App Mac gratuite et open source ; l’IA choisit les moments, vous relisez les clips signalés.',
      kicker: 'Usage · Podcasts',
      h1: 'Des clips de podcast, tirés de tout l’épisode.',
      intro: 'Déposez un podcast vidéo, dites combien de clips vous voulez et pour quelles plateformes. Reelfold lit la transcription, choisit les réponses qui tiennent seules et rend chacune dans tous les formats demandés, avec sous-titres, couverture et texte de publication.',
      img: 'talkinghead', figCaption: 'Clips verticaux avec sous-titres et panneau de notes, rendus sur un Mac.', figAlt: 'Une planche de clips verticaux où la créatrice parle face caméra, chacun avec des sous-titres incrustés et un court panneau de notes.',
      pointsT: 'Ce qu’un épisode vous donne',
      points: [
        { t: 'Des moments qui tiennent seuls', b: 'Le plan indique chaque clip avec son début, sa fin, un titre et la raison du choix. Modifiez une ligne avant tout rendu.' },
        { t: 'Des sous-titres bien placés', b: 'Les sous-titres restent dans la zone sûre de chaque plateforme, loin des boutons de TikTok ou de Xiaohongshu.' },
        { t: 'Hésitations : vous décidez', b: 'Pauses, tics de langage et faux départs sont proposés comme coupes. Les évidentes sont appliquées, les autres attendent votre accord.' },
        { t: 'Un dossier par plateforme', b: 'Chaque clip sort dans chaque format demandé, avec couverture, volume réglé et texte dans les limites de la plateforme.' },
      ],
      stepsT: 'De l’épisode à une semaine de clips',
      steps: [
        { t: 'Décrivez le lot', b: '« Dix clips d’environ une minute pour Shorts, Reels et Xiaohongshu. »' },
        { t: 'Validez le plan', b: 'Lisez les choix et l’estimation du coût d’IA. Remplacez un moment, raccourcissez-en un, ou validez tout.' },
        { t: 'Laissez tourner', b: 'Coupes, sous-titres, couvertures et exports tournent sur votre Mac, plusieurs clips à la fois.' },
        { t: 'Relisez les clips signalés', b: 'Les contrôles automatiques repèrent les mots manquants, le volume et la durée. Vous ne regardez que ceux-là.' },
      ],
      faq: [
        { q: 'Et les podcasts audio seulement ?', a: 'Reelfold est conçu pour la vidéo. Pour une émission audio, il faut d’abord une piste vidéo, par exemple une image fixe ou un plan filmé.' },
        { q: 'Quelle durée d’épisode ?', a: 'Les longs enregistrements sont justement sa raison d’être. Le lot de la page d’accueil partait d’un enregistrement de 72 minutes et a donné 24 clips.' },
        { q: 'Et avec deux intervenants ?', a: 'Oui. Les clips peuvent être en vertical, côte à côte ou en paysage, et les visages ou noms d’un invité peuvent être masqués s’il le souhaite.' },
      ],
      cta: 'Découpez votre prochain épisode sur votre Mac.',
      related: ['interview-clips', 'talking-head', 'compare/opus-clip'],
    },
    es: {
      nav: 'Clips de podcast',
      title: 'Podcast a clips cortos: todo un episodio de una vez | Reelfold',
      description: 'Convierte un videopodcast en clips verticales para TikTok, Reels, Shorts, Xiaohongshu y Douyin. App gratuita y de código abierto para Mac; la IA elige los momentos y tú revisas solo lo marcado.',
      kicker: 'Uso · Podcasts',
      h1: 'Clips de podcast, sacados de todo el episodio.',
      intro: 'Arrastra un videopodcast y di cuántos clips quieres y dónde van. Reelfold lee la transcripción, elige las respuestas que se sostienen solas y renderiza cada una para todas las plataformas que nombraste, con subtítulos, portada y texto.',
      img: 'talkinghead', figCaption: 'Clips verticales con subtítulos y panel de notas, renderizados en un Mac.', figAlt: 'Una hoja de contactos de clips verticales en los que habla la creadora, cada uno con subtítulos incrustados y un breve panel de notas.',
      pointsT: 'Lo que sale de un episodio',
      points: [
        { t: 'Momentos que se sostienen solos', b: 'El plan muestra cada clip con su inicio, su final, un título y por qué se eligió. Cambia una línea antes de renderizar.' },
        { t: 'Subtítulos en su sitio', b: 'Los subtítulos quedan dentro de la zona segura de cada plataforma, lejos de los botones de TikTok o Xiaohongshu.' },
        { t: 'Muletillas: decides tú', b: 'Pausas, muletillas y frases repetidas se proponen como cortes. Los claros se aplican; el resto espera tu sí.' },
        { t: 'Una carpeta por plataforma', b: 'Cada clip sale en cada formato pedido, con portada, volumen ajustado y texto dentro de los límites de la plataforma.' },
      ],
      stepsT: 'Del episodio a una semana de clips',
      steps: [
        { t: 'Describe el lote', b: '“Diez clips de este episodio, de un minuto más o menos, para Shorts, Reels y Xiaohongshu.”' },
        { t: 'Aprueba el plan', b: 'Revisa los momentos elegidos y la estimación de costo de IA. Cambia uno, acorta otro o apruébalo todo.' },
        { t: 'Deja que trabaje', b: 'Cortes, subtítulos, portadas y exportaciones se procesan en tu Mac, varios clips a la vez.' },
        { t: 'Revisa los pocos marcados', b: 'Los controles automáticos detectan palabras que faltan en los subtítulos, volumen y duración. Solo miras esos.' },
      ],
      faq: [
        { q: '¿Sirve para podcasts solo de audio?', a: 'Reelfold está hecho para video. En un programa solo de audio hace falta primero una pista de video, como una imagen fija o una cámara grabada.' },
        { q: '¿Cuánto puede durar el episodio?', a: 'Las grabaciones largas son justo su razón de ser. El lote de la página de inicio partió de una grabación de 72 minutos y dio 24 clips.' },
        { q: '¿Funciona con dos personas hablando?', a: 'Sí. Los clips pueden ir en vertical, lado a lado o en horizontal, y se pueden ocultar caras o rótulos con nombre si un invitado lo pide.' },
      ],
      cta: 'Corta tu próximo episodio en tu propio Mac.',
      related: ['interview-clips', 'talking-head', 'compare/opus-clip'],
    },
  },

  // ------------------------------------------------------------------ interviews / calls
  'interview-clips': {
    en: {
      nav: 'Interview clips',
      title: 'Interview and Zoom recordings to clips, faces masked | Reelfold',
      description: 'Turn Zoom, Meet or Teams interviews into short clips with captions. Mask guest faces and blur name labels when needed. Free, open-source Mac app that renders locally.',
      kicker: 'Use case · Interviews and calls',
      h1: 'Interview clips, with the guest’s privacy handled.',
      intro: 'Recorded a Zoom, Meet or Teams call? Reelfold finds the answers worth sharing and lays them out for each platform. If a guest would rather not appear, their face can be covered and their name label blurred, and the whole job runs on your Mac.',
      img: 'review', figCaption: 'Review: suggested cuts, each with a before and after preview.', figAlt: 'Review screen: four suggested cuts in one clip, each with a before and after preview and a checkbox.',
      pointsT: 'Made for recorded conversations',
      points: [
        { t: 'Layouts for calls', b: 'Vertical with the speaker in focus, a trio of tiles, or landscape. The same clip can go out in several layouts.' },
        { t: 'Face masking and label blur', b: 'Cover a guest’s face with a sticker and blur the name label under their tile, for every frame of the clip.' },
        { t: 'Regions you exclude', b: 'Tell the batch to ignore part of the screen, such as the participant column of a meeting window.' },
        { t: 'Local by default', b: 'The recording is cut and rendered on your Mac. The AI you connect sees the transcript it needs to plan.' },
      ],
      stepsT: 'From call to clips',
      steps: [
        { t: 'Drop in the recording', b: 'Add the call and say who should stay visible, and which platforms you need.' },
        { t: 'Check the plan', b: 'See which answers were picked and which parts of the screen are masked.' },
        { t: 'Render and check', b: 'Clips render locally; automatic checks flag captions, loudness and length problems.' },
        { t: 'Ask, then publish', b: 'Share the clips with your guest before they go out. You press publish on each platform.' },
      ],
      note: { t: 'Ask your guests first', b: 'Masking helps, but it doesn’t replace consent. Tell guests you plan to publish clips, and let them see the ones they appear in. Reelfold never publishes for you.' },
      faq: [
        { q: 'Which meeting apps work?', a: 'Any recording you have as a video file, including Zoom, Google Meet and Microsoft Teams recordings.' },
        { q: 'Does the masking follow the face?', a: 'Masks are placed per clip on the guest’s tile. Check the flagged clips in review before publishing, especially when the layout changes mid-call.' },
        { q: 'Do recordings leave my Mac?', a: 'Video and audio stay on your Mac. The transcript text goes to the AI you choose for planning, or nowhere if you use a local model.' },
      ],
      cta: 'Clip your next interview, privately.',
      related: ['podcast-clips', 'course-slicing', 'compare/descript'],
    },
    zh: {
      nav: '访谈切片',
      title: '访谈、会议录像切片，嘉宾人脸可打码 | 千剪',
      description: '把 Zoom、腾讯会议导出的录像、Meet、Teams 访谈剪成带字幕的短视频。需要时遮住嘉宾人脸、模糊姓名条。免费开源的 Mac 应用，本机渲染。',
      kicker: '场景 · 访谈与通话',
      h1: '访谈切片，嘉宾隐私也处理好。',
      intro: '录了一场 Zoom、Meet 或 Teams 通话？千剪找出值得分享的回答，按每个平台排好版。嘉宾不想露脸，可以遮住人脸、模糊姓名条，整个过程都在你的 Mac 上完成。',
      img: 'review', figCaption: '审核：每处建议剪掉的地方，都有前后对比预览。', figAlt: '审核界面：一条片段里四处建议剪掉的地方，每处都有前后对比预览和勾选框。',
      pointsT: '为录下来的对话而做',
      points: [
        { t: '适合通话的版式', b: '竖屏突出说话的人、三人宫格，或者横屏。同一条片段可以同时出几种版式。' },
        { t: '遮脸和模糊姓名条', b: '用贴纸遮住嘉宾的脸，模糊其画面下方的姓名条，覆盖整条片段的每一帧。' },
        { t: '指定不要的区域', b: '告诉这一批忽略画面的某一部分，比如会议窗口右侧的参会者一栏。' },
        { t: '默认在本机', b: '录像在你的 Mac 上剪辑和渲染。你接入的 AI 只看到规划所需的文字稿。' },
      ],
      stepsT: '从通话到片段',
      steps: [
        { t: '拖进录像', b: '加入通话录像，说清谁要露脸、发哪些平台。' },
        { t: '检查计划', b: '看选了哪些回答，画面哪些部分会被遮住。' },
        { t: '渲染并检查', b: '片段在本机渲染；自动检查会标出字幕、响度和时长问题。' },
        { t: '先问，再发', b: '发出去之前先给嘉宾看。每个平台都由你按下发布。' },
      ],
      note: { t: '先征得嘉宾同意', b: '打码能帮忙，但代替不了同意。告诉嘉宾你打算发片段，让他们看看自己出现的那几条。千剪从不替你发帖。' },
      faq: [
        { q: '支持哪些会议软件？', a: '只要录像是视频文件就行，包括 Zoom、Google Meet、Microsoft Teams 和腾讯会议的录制文件。' },
        { q: '遮脸会跟着人脸走吗？', a: '遮挡按片段放在嘉宾的画面格上。发布前在审核里看一下被标出的片段，尤其是通话中途换了布局的时候。' },
        { q: '录像会离开我的 Mac 吗？', a: '视频和音频都留在你的 Mac 上。文字稿会发给你选的 AI 用来规划；用本地模型则哪里都不发。' },
      ],
      cta: '下一场访谈，安心地切。',
      related: ['podcast-clips', 'course-slicing', 'compare/descript'],
    },
    fr: {
      nav: 'Clips d’interview',
      title: 'Interviews et appels Zoom en clips, visages masqués | Reelfold',
      description: 'Transformez des interviews Zoom, Meet ou Teams en clips courts sous-titrés. Masquez le visage d’un invité et floutez son nom si besoin. App Mac gratuite et open source, rendu en local.',
      kicker: 'Usage · Interviews et appels',
      h1: 'Des clips d’interview, sans exposer vos invités.',
      intro: 'Vous avez enregistré un appel Zoom, Meet ou Teams ? Reelfold repère les réponses à partager et les met en page pour chaque plateforme. Si un invité préfère ne pas apparaître, son visage peut être couvert et son nom flouté, le tout sur votre Mac.',
      img: 'review', figCaption: 'Relecture : chaque coupe proposée, avec un aperçu avant et après.', figAlt: 'Écran de relecture : quatre coupes proposées dans un clip, chacune avec un aperçu avant et après et une case à cocher.',
      pointsT: 'Pensé pour les conversations enregistrées',
      points: [
        { t: 'Des mises en page d’appel', b: 'Vertical centré sur la personne qui parle, trois vignettes, ou paysage. Un même clip peut sortir dans plusieurs mises en page.' },
        { t: 'Visages masqués, noms floutés', b: 'Couvrez le visage d’un invité avec un sticker et floutez le nom sous sa vignette, sur toutes les images du clip.' },
        { t: 'Zones exclues', b: 'Demandez au lot d’ignorer une partie de l’écran, comme la colonne des participants d’une réunion.' },
        { t: 'En local par défaut', b: 'L’enregistrement est coupé et rendu sur votre Mac. L’IA que vous branchez voit la transcription nécessaire au plan.' },
      ],
      stepsT: 'De l’appel aux clips',
      steps: [
        { t: 'Déposez l’enregistrement', b: 'Ajoutez l’appel, dites qui doit rester visible et pour quelles plateformes.' },
        { t: 'Vérifiez le plan', b: 'Voyez quelles réponses ont été retenues et quelles zones de l’écran sont masquées.' },
        { t: 'Rendu et contrôles', b: 'Les clips sont rendus en local ; les contrôles signalent les problèmes de sous-titres, de volume et de durée.' },
        { t: 'Demandez, puis publiez', b: 'Montrez les clips à votre invité avant leur sortie. C’est vous qui publiez sur chaque plateforme.' },
      ],
      note: { t: 'Demandez d’abord à vos invités', b: 'Le masquage aide, mais ne remplace pas le consentement. Prévenez vos invités que vous comptez publier des clips et montrez-leur ceux où ils apparaissent. Reelfold ne publie jamais à votre place.' },
      faq: [
        { q: 'Quelles applis de réunion ?', a: 'Tout enregistrement disponible en fichier vidéo, y compris ceux de Zoom, Google Meet et Microsoft Teams.' },
        { q: 'Le masque suit-il le visage ?', a: 'Les masques sont placés par clip sur la vignette de l’invité. Vérifiez les clips signalés en relecture avant de publier, surtout si la mise en page change pendant l’appel.' },
        { q: 'Les enregistrements quittent-ils mon Mac ?', a: 'La vidéo et l’audio restent sur votre Mac. Le texte de la transcription part vers l’IA choisie pour le plan, ou nulle part avec un modèle local.' },
      ],
      cta: 'Découpez votre prochaine interview, en toute discrétion.',
      related: ['podcast-clips', 'course-slicing', 'compare/descript'],
    },
    es: {
      nav: 'Clips de entrevistas',
      title: 'Entrevistas y llamadas de Zoom a clips, con caras ocultas | Reelfold',
      description: 'Convierte entrevistas de Zoom, Meet o Teams en clips cortos con subtítulos. Oculta la cara de un invitado y difumina su nombre si hace falta. App gratuita y de código abierto para Mac, con renderizado local.',
      kicker: 'Uso · Entrevistas y llamadas',
      h1: 'Clips de entrevistas, cuidando a tus invitados.',
      intro: '¿Grabaste una llamada de Zoom, Meet o Teams? Reelfold encuentra las respuestas que vale la pena compartir y las adapta a cada plataforma. Si un invitado prefiere no salir, se puede tapar su cara y difuminar su nombre, todo en tu Mac.',
      img: 'review', figCaption: 'Revisión: cada corte sugerido, con vista previa de antes y después.', figAlt: 'Pantalla de revisión: cuatro cortes sugeridos en un clip, cada uno con vista previa de antes y después y una casilla.',
      pointsT: 'Pensado para conversaciones grabadas',
      points: [
        { t: 'Diseños para llamadas', b: 'Vertical con quien habla en primer plano, tres recuadros o formato horizontal. El mismo clip puede salir en varios diseños.' },
        { t: 'Caras tapadas y nombres difuminados', b: 'Tapa la cara de un invitado con un sticker y difumina el rótulo con su nombre, en todos los fotogramas del clip.' },
        { t: 'Zonas que se ignoran', b: 'Indica al lote que ignore una parte de la pantalla, como la columna de participantes de una reunión.' },
        { t: 'Local por defecto', b: 'La grabación se corta y se renderiza en tu Mac. La IA que conectes ve la transcripción que necesita para planificar.' },
      ],
      stepsT: 'De la llamada a los clips',
      steps: [
        { t: 'Arrastra la grabación', b: 'Añade la llamada y di quién debe quedar visible y para qué plataformas.' },
        { t: 'Revisa el plan', b: 'Mira qué respuestas se eligieron y qué partes de la pantalla se ocultan.' },
        { t: 'Renderiza y revisa', b: 'Los clips se renderizan en local; los controles automáticos marcan problemas de subtítulos, volumen y duración.' },
        { t: 'Pregunta y luego publica', b: 'Enseña los clips a tu invitado antes de publicarlos. Tú pulsas publicar en cada plataforma.' },
      ],
      note: { t: 'Pregunta primero a tus invitados', b: 'Ocultar caras ayuda, pero no sustituye el consentimiento. Avisa a tus invitados de que vas a publicar clips y déjales ver aquellos en los que aparecen. Reelfold nunca publica por ti.' },
      faq: [
        { q: '¿Con qué apps de reuniones funciona?', a: 'Con cualquier grabación que tengas como archivo de video, incluidas las de Zoom, Google Meet y Microsoft Teams.' },
        { q: '¿El sticker sigue la cara?', a: 'Las máscaras se colocan por clip sobre el recuadro del invitado. Revisa los clips marcados antes de publicar, sobre todo si el diseño de la llamada cambia a mitad.' },
        { q: '¿Las grabaciones salen de mi Mac?', a: 'El video y el audio se quedan en tu Mac. El texto de la transcripción va a la IA que elijas para planificar, o a ninguna parte si usas un modelo local.' },
      ],
      cta: 'Corta tu próxima entrevista, con discreción.',
      related: ['podcast-clips', 'course-slicing', 'compare/descript'],
    },
  },

  // ------------------------------------------------------------------ courses / lectures
  'course-slicing': {
    en: {
      nav: 'Course slicing',
      title: 'Lecture to short videos: slice a recorded course | Reelfold',
      description: 'Slice a recorded lecture, webinar or livestream into short lessons for Xiaohongshu, Douyin, Shorts and Bilibili, with code and slides kept readable. Free, open-source Mac app.',
      kicker: 'Use case · Courses and lectures',
      h1: 'One recorded class, a series of short lessons.',
      intro: 'Lectures, webinars and livestream replays hold dozens of ideas that work on their own. Reelfold finds them, keeps the code and slides readable in a vertical frame, and numbers the clips as a series.',
      img: 'longform', figCaption: 'Vertical slices from a recorded lecture: a title band over a readable crop of the code.', figAlt: 'Frames from vertical lecture slices: a series title band at the top and a zoomed crop of code or slides below.',
      pointsT: 'Built for screens full of text',
      points: [
        { t: 'Readable code and slides', b: 'Vertical slices crop and zoom the part of the screen that matters, so a line of code survives a phone screen.' },
        { t: 'A series, not a pile', b: 'Each clip gets a number, a series name and a title, so viewers can find the next one.' },
        { t: 'Notes panels', b: 'When the screen is static, a short notes panel carries the key point of the clip.' },
        { t: 'Private parts left out', b: 'Small talk, student questions and side conversations can be skipped, and screen regions excluded.' },
      ],
      stepsT: 'A real example',
      steps: [
        { t: '72 minutes in', b: 'One recorded lecture on retrieval-augmented generation, screen share plus voice.' },
        { t: '24 clips planned', b: 'Each about a minute, picked for one clear point, with the off-topic parts left out.' },
        { t: '96 files out', b: 'Four formats per clip: Xiaohongshu 3:4 and 9:16, Douyin and YouTube Shorts.' },
        { t: '21 of 24 passed', b: 'Three were flagged for a person to check. The AI cost for the whole run was $0.73.' },
      ],
      faq: [
        { q: 'Can I keep a long version too?', a: 'Yes. The same recording can become a cut course video with chapters as well as the short episodes.' },
        { q: 'What about student voices or faces?', a: 'Leave those parts out of the plan, exclude the screen region where they appear, or mask them. Ask before you publish anyone else.' },
        { q: 'Does it handle Chinese technical terms?', a: 'You can give the batch a glossary so terms like “chunk” or “reranker” are spelled the same way in every caption.' },
      ],
      cta: 'Turn your next class into a series.',
      related: ['talking-head', 'studios', 'platforms'],
    },
    zh: {
      nav: '课程切片',
      title: '课程切片：把录播课、直播回放剪成短视频 | 千剪',
      description: '把录播课、讲座、直播回放切成小红书、抖音、Shorts、B站的短课，代码和幻灯片都看得清。免费开源的 Mac 应用。',
      kicker: '场景 · 课程与讲座',
      h1: '一节录播课，切成一组短课。',
      intro: '讲座、直播回放和录播课里，藏着几十个能单独讲清楚的点。千剪把它们找出来，在竖屏里也让代码和幻灯片看得清，再给片段编号，排成一个系列。',
      img: 'longform', figCaption: '录播课的竖屏切片：上方标题条，下方是放大后看得清的代码。', figAlt: '竖屏课程切片的几帧：顶部是系列标题条，下面是放大裁切后的代码或幻灯片。',
      pointsT: '为满屏文字的画面而做',
      points: [
        { t: '代码、幻灯片看得清', b: '竖屏切片会裁切并放大画面里真正要看的部分，一行代码在手机上也读得出来。' },
        { t: '成系列，不是一堆', b: '每条都有编号、系列名和标题，观众能找到下一集。' },
        { t: '记笔记面板', b: '画面不动的时候，一个简短的笔记面板把这条的要点写出来。' },
        { t: '私人内容不出镜', b: '闲聊、学生提问、题外话都可以跳过，画面里不该出现的区域也能排除。' },
      ],
      stepsT: '一个真实例子',
      steps: [
        { t: '输入 72 分钟', b: '一节讲 RAG（检索增强生成）的录播课，屏幕共享加讲解。' },
        { t: '规划 24 条', b: '每条一分钟左右，各讲清一个点，跑题的部分都去掉。' },
        { t: '输出 96 个文件', b: '每条四种尺寸：小红书 3:4 和 9:16、抖音、YouTube Shorts。' },
        { t: '24 条通过 21 条', b: '3 条被标出来交给人看。整批的 AI 费用是 0.73 美元。' },
      ],
      faq: [
        { q: '还能保留一个长版本吗？', a: '可以。同一条录像既能剪成带章节的完整课程视频，也能切成短集。' },
        { q: '学生的声音或画面怎么办？', a: '可以在计划里去掉这些部分，排除他们出现的画面区域，或者打码。发布别人之前，先问一声。' },
        { q: '中文里夹着的技术词能处理吗？', a: '可以给这一批一份术语表，让 “chunk”“reranker” 这类词在每条字幕里写法一致。' },
      ],
      cta: '下一节课，切成一个系列。',
      related: ['talking-head', 'studios', 'platforms'],
    },
    fr: {
      nav: 'Découper un cours',
      title: 'Cours en vidéos courtes : découper un cours enregistré | Reelfold',
      description: 'Découpez un cours, un webinaire ou un live enregistré en leçons courtes pour Xiaohongshu, Douyin, Shorts et Bilibili, avec un code et des slides lisibles. App Mac gratuite et open source.',
      kicker: 'Usage · Cours et conférences',
      h1: 'Un cours enregistré, une série de leçons courtes.',
      intro: 'Cours, webinaires et rediffusions de live contiennent des dizaines d’idées qui tiennent seules. Reelfold les repère, garde le code et les slides lisibles en vertical, et numérote les clips comme une série.',
      img: 'longform', figCaption: 'Extraits verticaux d’un cours : un bandeau titre au-dessus d’un code lisible.', figAlt: 'Images d’extraits verticaux d’un cours : un bandeau avec le nom de la série en haut et un recadrage zoomé du code ou des slides en dessous.',
      pointsT: 'Pensé pour les écrans pleins de texte',
      points: [
        { t: 'Code et slides lisibles', b: 'Les extraits verticaux recadrent et agrandissent la partie utile de l’écran, pour qu’une ligne de code reste lisible sur un téléphone.' },
        { t: 'Une série, pas un tas', b: 'Chaque clip reçoit un numéro, un nom de série et un titre : on trouve facilement le suivant.' },
        { t: 'Panneaux de notes', b: 'Quand l’écran ne bouge pas, un court panneau de notes porte l’idée clé du clip.' },
        { t: 'Le privé reste dehors', b: 'Bavardages, questions d’élèves et apartés peuvent être écartés, et des zones de l’écran exclues.' },
      ],
      stepsT: 'Un exemple réel',
      steps: [
        { t: '72 minutes en entrée', b: 'Un cours enregistré sur le RAG (génération augmentée par la recherche), partage d’écran et voix.' },
        { t: '24 clips planifiés', b: 'Environ une minute chacun, choisis pour une idée claire, sans les passages hors sujet.' },
        { t: '96 fichiers en sortie', b: 'Quatre formats par clip : Xiaohongshu 3:4 et 9:16, Douyin et YouTube Shorts.' },
        { t: '21 sur 24 validés', b: 'Trois ont été signalés pour une vérification humaine. Coût d’IA du lot entier : 0,73 $.' },
      ],
      faq: [
        { q: 'Puis-je garder une version longue ?', a: 'Oui. Le même enregistrement peut devenir une vidéo de cours montée avec chapitres, en plus des épisodes courts.' },
        { q: 'Et la voix ou le visage des élèves ?', a: 'Retirez ces passages du plan, excluez la zone de l’écran où ils apparaissent, ou masquez-les. Demandez avant de publier qui que ce soit d’autre.' },
        { q: 'Et le jargon technique ?', a: 'Vous pouvez donner un glossaire au lot pour que des termes comme « chunk » ou « reranker » s’écrivent de la même façon dans tous les sous-titres.' },
      ],
      cta: 'Faites de votre prochain cours une série.',
      related: ['talking-head', 'studios', 'platforms'],
    },
    es: {
      nav: 'Cortar un curso',
      title: 'Clase a videos cortos: corta un curso grabado | Reelfold',
      description: 'Corta una clase, un webinar o un directo grabado en lecciones cortas para Xiaohongshu, Douyin, Shorts y Bilibili, con el código y las diapositivas legibles. App gratuita y de código abierto para Mac.',
      kicker: 'Uso · Cursos y clases',
      h1: 'Una clase grabada, una serie de lecciones cortas.',
      intro: 'Clases, webinars y directos grabados esconden decenas de ideas que se sostienen solas. Reelfold las encuentra, mantiene legibles el código y las diapositivas en vertical y numera los clips como una serie.',
      img: 'longform', figCaption: 'Cortes verticales de una clase: una franja con el título sobre un recorte legible del código.', figAlt: 'Fotogramas de cortes verticales de una clase: arriba una franja con el nombre de la serie y debajo un recorte ampliado del código o las diapositivas.',
      pointsT: 'Pensado para pantallas llenas de texto',
      points: [
        { t: 'Código y diapositivas legibles', b: 'Los cortes verticales recortan y amplían la parte de la pantalla que importa, para que una línea de código se lea en un móvil.' },
        { t: 'Una serie, no un montón', b: 'Cada clip lleva número, nombre de serie y título, así se encuentra el siguiente.' },
        { t: 'Paneles de notas', b: 'Cuando la pantalla no se mueve, un breve panel de notas lleva la idea clave del clip.' },
        { t: 'Lo privado se queda fuera', b: 'Charla informal, preguntas de alumnos y apartes se pueden saltar, y se pueden excluir zonas de la pantalla.' },
      ],
      stepsT: 'Un ejemplo real',
      steps: [
        { t: '72 minutos de entrada', b: 'Una clase grabada sobre RAG (generación aumentada por recuperación), con pantalla compartida y voz.' },
        { t: '24 clips planificados', b: 'De un minuto más o menos, cada uno elegido por una idea clara, sin las partes que se salen del tema.' },
        { t: '96 archivos de salida', b: 'Cuatro formatos por clip: Xiaohongshu 3:4 y 9:16, Douyin y YouTube Shorts.' },
        { t: '21 de 24 aprobados', b: 'Tres quedaron marcados para que los revisara una persona. El costo de IA de todo el lote fue de 0,73 US$.' },
      ],
      faq: [
        { q: '¿Puedo conservar también una versión larga?', a: 'Sí. La misma grabación puede convertirse en un video de curso editado con capítulos, además de los episodios cortos.' },
        { q: '¿Y la voz o la cara de los alumnos?', a: 'Quita esas partes del plan, excluye la zona de la pantalla donde aparecen u ocúltalas. Pregunta antes de publicar a otra persona.' },
        { q: '¿Respeta los términos técnicos?', a: 'Puedes darle al lote un glosario para que términos como “chunk” o “reranker” se escriban igual en todos los subtítulos.' },
      ],
      cta: 'Convierte tu próxima clase en una serie.',
      related: ['talking-head', 'studios', 'platforms'],
    },
  },

  // ------------------------------------------------------------------ talking head
  'talking-head': {
    en: {
      nav: 'Talking-head shorts',
      title: 'Remove filler words and pauses from talking-head video | Reelfold',
      description: 'Cut pauses, filler words, repeats and restarts from talking-head videos, add captions, punch-ins and a cover, and export for every platform. Free, open-source Mac app; you confirm the uncertain cuts.',
      kicker: 'Use case · Talking head',
      h1: 'Talking-head videos, without the ums.',
      intro: 'Reelfold finds the pauses, filler words, repeats and restarts in a talking-head recording. Clear ones are cut on word boundaries; the ones it isn’t sure about are listed for you to keep or cut. Then come captions, punch-ins, a cover and one export per platform.',
      img: 'textedit', figCaption: 'Edit with AI: filler words, long pauses and likely caption typos, listed before anything is cut.', figAlt: 'The clip editor: a vertical preview, the transcript with fillers and pauses marked, and a side panel suggesting to remove 12 filler words and tighten 7 long pauses.',
      pointsT: 'Cleanup you can trust',
      points: [
        { t: 'Cuts on word boundaries', b: 'Every cut lands between words and on an exact frame, so no syllable is clipped.' },
        { t: 'You confirm the unsure ones', b: 'Uncertain cuts come as a short list with the words before and after. Reply “cut 3, 5, keep 7”, or tick boxes in the app.' },
        { t: 'Checked after cutting', b: 'The audio is transcribed again after cleanup to make sure no content word was lost.' },
        { t: 'Three strengths', b: 'Gentle, standard or tight. Pick per video, or set a default per client.' },
      ],
      stepsT: 'What happens to one recording',
      steps: [
        { t: 'Clean up speech', b: 'Pauses, fillers, repeats and restarts are found and sorted into sure and unsure.' },
        { t: 'Tighten the pace', b: 'An optional speed-up with pitch kept, so the video feels brisk without sounding rushed.' },
        { t: 'Add the layer on top', b: 'Captions, punch-ins, pop words, a notes panel and a progress bar, styled the same across a series.' },
        { t: 'Cover and copy', b: 'A cover for each platform’s size and post copy within each platform’s limits.' },
      ],
      faq: [
        { q: 'Does it handle Chinese filler words?', a: 'Yes. It knows common fillers in Chinese (such as 就是, 然后, 那个) and English, and you can add your own words per client.' },
        { q: 'Can I edit by transcript?', a: 'Yes. The clip editor shows the transcript with fillers and pauses marked, and you can cut a range by selecting words.' },
        { q: 'Will it change what I said?', a: 'Cuts only remove time. Caption corrections that are guesses are marked so a person checks them; the audio itself is never rewritten.' },
      ],
      cta: 'Clean up your next take.',
      related: ['course-slicing', 'podcast-clips', 'compare/descript'],
    },
    zh: {
      nav: '口播剪辑',
      title: '口播视频去气口、去口头禅、删停顿 | 千剪',
      description: '自动找出口播视频里的停顿、口头禅、重复和说错重来，加字幕、放大镜头和封面，导出各平台尺寸。免费开源的 Mac 应用，拿不准的剪辑由你确认。',
      kicker: '场景 · 口播',
      h1: '口播视频，去掉气口和口头禅。',
      intro: '千剪会找出口播录像里的停顿、口头禅、重复和说错重来。把握大的按词边界直接剪掉；拿不准的列出来，由你决定留还是剪。之后再加字幕、放大镜头、封面，每个平台各导一版。',
      img: 'textedit', figCaption: '用 AI 编辑：口头禅、长停顿、可能的字幕错字，剪之前先列出来。', figAlt: '片段编辑器：左边是竖屏预览，下方是标出口头禅和停顿的文字稿，右侧建议删掉 12 个口头禅、收紧 7 处长停顿。',
      pointsT: '放心交给它的去气口',
      points: [
        { t: '按词边界剪', b: '每一刀都落在两个词之间、精确到帧，不会剪掉半个字。' },
        { t: '拿不准的由你确认', b: '不确定的剪辑会列成一张短表，带上前后文。回一句 “确认 3,5 / 保留 7”，或者在应用里勾选。' },
        { t: '剪完再核一遍', b: '去气口之后会重新转写一遍音频，确认没有丢掉有内容的词。' },
        { t: '三档力度', b: '轻、标准、紧。每条单独选，或者按客户设默认值。' },
      ],
      stepsT: '一条录像会经过什么',
      steps: [
        { t: '整理口播', b: '找出停顿、口头禅、重复和说错重来，分成有把握和拿不准两类。' },
        { t: '调节语速', b: '可选加速，保持音调不变，节奏利落又不显得赶。' },
        { t: '叠加上层', b: '字幕、放大镜头、弹出关键词、记笔记面板和进度条，一个系列风格统一。' },
        { t: '封面和文案', b: '每个平台尺寸各一张封面，文案字数按平台限制来。' },
      ],
      faq: [
        { q: '中文口头禅能识别吗？', a: '能。它认得中文（比如“就是”“然后”“那个”）和英文的常见口头禅，你也可以按客户添加自己的词。' },
        { q: '能直接改文字稿来剪吗？', a: '能。片段编辑器里有标出口头禅和停顿的文字稿，选中一段字就能剪掉对应的画面。' },
        { q: '会改掉我说的话吗？', a: '剪辑只会删掉时间。字幕里凡是猜测的修改都会标出来，让人核对；音频本身从不被改写。' },
      ],
      cta: '下一条口播，交给千剪去气口。',
      related: ['course-slicing', 'podcast-clips', 'compare/descript'],
    },
    fr: {
      nav: 'Vidéos face caméra',
      title: 'Retirer les hésitations et les silences d’une vidéo face caméra | Reelfold',
      description: 'Coupez les silences, hésitations, répétitions et faux départs de vos vidéos face caméra, ajoutez sous-titres, zooms et couverture, puis exportez pour chaque plateforme. App Mac gratuite et open source ; vous validez les coupes incertaines.',
      kicker: 'Usage · Face caméra',
      h1: 'Des vidéos face caméra, sans les « euh ».',
      intro: 'Reelfold repère les silences, hésitations, répétitions et faux départs d’un enregistrement face caméra. Les cas évidents sont coupés entre deux mots ; les autres vous sont listés pour garder ou couper. Viennent ensuite sous-titres, zooms, couverture et un export par plateforme.',
      img: 'textedit', figCaption: 'Modifier avec l’IA : hésitations, longs silences et coquilles probables, listés avant toute coupe.', figAlt: 'L’éditeur de clip : un aperçu vertical, la transcription avec hésitations et silences marqués, et un panneau qui propose de retirer 12 hésitations et de raccourcir 7 longs silences.',
      pointsT: 'Un nettoyage digne de confiance',
      points: [
        { t: 'Des coupes entre les mots', b: 'Chaque coupe tombe entre deux mots, à l’image près : aucune syllabe n’est rognée.' },
        { t: 'Vous validez les cas douteux', b: 'Les coupes incertaines arrivent en courte liste, avec les mots avant et après. Répondez « coupe 3, 5, garde 7 », ou cochez dans l’app.' },
        { t: 'Vérifié après coupe', b: 'L’audio est retranscrit après le nettoyage pour s’assurer qu’aucun mot utile n’a disparu.' },
        { t: 'Trois intensités', b: 'Douce, standard ou serrée. À choisir par vidéo, ou par défaut pour chaque client.' },
      ],
      stepsT: 'Ce que devient un enregistrement',
      steps: [
        { t: 'Nettoyer la parole', b: 'Silences, hésitations, répétitions et faux départs sont repérés et triés en sûrs et incertains.' },
        { t: 'Resserrer le rythme', b: 'Une accélération facultative qui garde la hauteur de la voix : plus vif, sans paraître pressé.' },
        { t: 'Ajouter l’habillage', b: 'Sous-titres, zooms, mots mis en avant, panneau de notes et barre de progression, cohérents sur toute une série.' },
        { t: 'Couverture et texte', b: 'Une couverture au format de chaque plateforme et un texte de publication dans ses limites.' },
      ],
      faq: [
        { q: 'Et les hésitations en français ?', a: 'Il reconnaît les hésitations courantes en chinois et en anglais, et vous pouvez ajouter vos propres tics de langage par client, en français comme ailleurs.' },
        { q: 'Puis-je monter à partir du texte ?', a: 'Oui. L’éditeur de clip affiche la transcription avec hésitations et silences marqués, et vous coupez un passage en sélectionnant les mots.' },
        { q: 'Va-t-il changer ce que j’ai dit ?', a: 'Les coupes ne font que retirer du temps. Les corrections de sous-titres qui sont des suppositions sont signalées pour qu’une personne les vérifie ; l’audio n’est jamais réécrit.' },
      ],
      cta: 'Nettoyez votre prochaine prise.',
      related: ['course-slicing', 'podcast-clips', 'compare/descript'],
    },
    es: {
      nav: 'Videos a cámara',
      title: 'Quita muletillas y pausas de tus videos a cámara | Reelfold',
      description: 'Elimina pausas, muletillas, repeticiones y frases empezadas de nuevo en videos a cámara, añade subtítulos, zooms y portada, y exporta para cada plataforma. App gratuita y de código abierto para Mac; tú confirmas los cortes dudosos.',
      kicker: 'Uso · Videos a cámara',
      h1: 'Videos a cámara, sin los “eh”.',
      intro: 'Reelfold encuentra las pausas, muletillas, repeticiones y frases empezadas de nuevo de una grabación a cámara. Las claras se cortan entre palabras; las dudosas se te muestran para que decidas. Después vienen los subtítulos, los zooms, la portada y una exportación por plataforma.',
      img: 'textedit', figCaption: 'Editar con IA: muletillas, pausas largas y posibles erratas, listadas antes de cortar nada.', figAlt: 'El editor de clips: una vista previa vertical, la transcripción con muletillas y pausas marcadas y un panel que sugiere quitar 12 muletillas y acortar 7 pausas largas.',
      pointsT: 'Una limpieza de confianza',
      points: [
        { t: 'Cortes entre palabras', b: 'Cada corte cae entre dos palabras y en el fotograma exacto, sin comerse ninguna sílaba.' },
        { t: 'Tú confirmas las dudas', b: 'Los cortes dudosos llegan en una lista breve con las palabras de antes y después. Responde “corta 3 y 5, deja 7” o marca las casillas en la app.' },
        { t: 'Comprobado después', b: 'Tras la limpieza se vuelve a transcribir el audio para asegurar que no se perdió ninguna palabra con contenido.' },
        { t: 'Tres intensidades', b: 'Suave, estándar o ajustada. Elígela por video o fija una por defecto para cada cliente.' },
      ],
      stepsT: 'Qué le pasa a una grabación',
      steps: [
        { t: 'Limpiar el habla', b: 'Se detectan pausas, muletillas, repeticiones y frases empezadas de nuevo, separadas en seguras y dudosas.' },
        { t: 'Ajustar el ritmo', b: 'Una aceleración opcional que conserva el tono de la voz: ágil, sin sonar apurado.' },
        { t: 'Añadir la capa de arriba', b: 'Subtítulos, zooms, palabras destacadas, panel de notas y barra de progreso, con el mismo estilo en toda una serie.' },
        { t: 'Portada y texto', b: 'Una portada al tamaño de cada plataforma y un texto dentro de sus límites.' },
      ],
      faq: [
        { q: '¿Detecta muletillas en español?', a: 'Reconoce las muletillas habituales en chino y en inglés, y puedes añadir las tuyas por cliente, también en español.' },
        { q: '¿Puedo editar desde la transcripción?', a: 'Sí. El editor de clips muestra la transcripción con muletillas y pausas marcadas, y puedes cortar un tramo seleccionando palabras.' },
        { q: '¿Cambiará lo que dije?', a: 'Los cortes solo quitan tiempo. Las correcciones de subtítulos que son suposiciones se marcan para que las revise una persona; el audio nunca se reescribe.' },
      ],
      cta: 'Limpia tu próxima toma.',
      related: ['course-slicing', 'podcast-clips', 'compare/descript'],
    },
  },

  // ------------------------------------------------------------------ studios
  studios: {
    en: {
      nav: 'Studios and batches',
      title: 'Batch video editing for studios and client work | Reelfold',
      description: 'Run the same edit across many recordings: a pilot first, parallel runs on your Mac, exception-only review and one delivery folder per platform. Free, open-source batch video app for Mac.',
      kicker: 'Use case · Studios',
      h1: 'Client batches, run like a production line.',
      intro: 'When a client sends twenty recordings a week, the work is the same treatment applied many times, plus a few exceptions. Reelfold runs a small pilot first, then the whole batch in parallel, and sends you only what its checks flag.',
      img: 'typing', figCaption: 'One request for three livestreams: nine clips, about a minute each, one a day from Thursday.', figAlt: 'The Reelfold home screen with a request typed in: cut this week’s three livestreams into Xiaohongshu and Douyin clips, with the plan summary below.',
      pointsT: 'What a studio needs',
      points: [
        { t: 'A workspace per client', b: 'Style, platforms, glossary, filler rules and brand colours apply only to that client’s batches.' },
        { t: 'Pilot before the batch', b: 'A few clips run end to end first, so one mistake doesn’t repeat across a hundred jobs.' },
        { t: 'Exception-only review', b: 'Automatic checks for loudness, sync, missing caption words, text under app buttons, length and title length. Only red items reach you.' },
        { t: 'A delivery package', b: 'One folder per platform, a schedule, post copy and a manifest with checksums, ready to hand over.' },
      ],
      stepsT: 'A week for one client',
      steps: [
        { t: 'Import the recordings', b: 'Drop a folder. Each file is planned with the client’s settings.' },
        { t: 'Run the pilot', b: 'Check two or three clips. Fix the plan once, for every job after.' },
        { t: 'Run the batch', b: 'Jobs run in parallel, and an interrupted run picks up where it stopped.' },
        { t: 'Deliver', b: 'Review the flagged few, then hand over the folders or fill each upload page yourself.' },
      ],
      faq: [
        { q: 'Is there a per-seat or per-minute fee?', a: 'No. Reelfold is free and MIT licensed. You pay only for the AI you connect: the 72-minute batch on our home page cost $0.73.' },
        { q: 'Can my client publish themselves?', a: 'Yes. The delivery folder has the videos, covers, copy and a schedule. The publishing checklist reminds them to tick each platform’s AI label.' },
        { q: 'Can I script it?', a: 'Yes. The engine underneath is open source and runs from the command line or as a Claude Code skill.' },
      ],
      cta: 'Run your next client batch on your Mac.',
      related: ['course-slicing', 'interview-clips', 'compare/capcut'],
    },
    zh: {
      nav: '工作室批量',
      title: '视频批量剪辑：工作室和客户批量单 | 千剪',
      description: '同一套剪辑跑完很多条录像：先跑试点，再在 Mac 上并行跑完，只审核被标出的，每个平台交付一个文件夹。免费开源的 Mac 批量剪辑应用。',
      kicker: '场景 · 工作室',
      h1: '客户的批量单，像流水线一样跑。',
      intro: '客户每周发来二十条录像，活儿其实是同一套处理重复很多遍，再加几个例外。千剪先跑一个小试点，再并行跑完整批，只把没通过检查的交给你。',
      img: 'typing', figCaption: '一句话交代三场直播：九条片段，每条约一分钟，从周四起每天一条。', figAlt: '千剪首页，输入框里写着：把这周三场直播剪成小红书和抖音片段，下方是计划摘要。',
      pointsT: '工作室需要的',
      points: [
        { t: '每个客户一个空间', b: '风格、平台、术语表、口头禅规则和品牌色，只作用于这个客户的批次。' },
        { t: '先试点，再开跑', b: '先让几条从头跑到尾，免得一个错误在一百个任务里重复。' },
        { t: '只审例外', b: '自动检查响度、音画同步、字幕漏字、文字被按钮挡住、时长和标题长度。只有红色的才到你这里。' },
        { t: '交付包', b: '每个平台一个文件夹，加上排期表、文案和带校验码的清单，直接交给客户。' },
      ],
      stepsT: '一个客户的一周',
      steps: [
        { t: '导入录像', b: '拖进一个文件夹，每个文件都按这个客户的设置规划。' },
        { t: '跑试点', b: '看两三条。计划改一次，之后每个任务都生效。' },
        { t: '跑整批', b: '任务并行跑；中途停下，也能从中断的地方接着跑。' },
        { t: '交付', b: '看一眼被标出的几条，然后交出文件夹，或者自己填好每个平台的上传页。' },
      ],
      faq: [
        { q: '按席位或按分钟收费吗？', a: '不收。千剪免费，MIT 开源。你只为接入的 AI 付钱：首页那批 72 分钟的录像，AI 费用是 0.73 美元。' },
        { q: '客户能自己发吗？', a: '能。交付文件夹里有视频、封面、文案和排期表。发布清单会提醒他们在每个平台勾选 AI 标注。' },
        { q: '能写脚本自动化吗？', a: '能。底层引擎开源，可以在命令行里跑，也可以作为 Claude Code 技能使用。' },
      ],
      cta: '下一个客户的批量单，在你的 Mac 上跑。',
      related: ['course-slicing', 'interview-clips', 'compare/capcut'],
    },
    fr: {
      nav: 'Studios et lots',
      title: 'Montage vidéo par lots pour studios et clients | Reelfold',
      description: 'Appliquez le même montage à de nombreux enregistrements : un pilote d’abord, des tâches en parallèle sur votre Mac, une relecture des seules exceptions et un dossier de livraison par plateforme. App Mac gratuite et open source.',
      kicker: 'Usage · Studios',
      h1: 'Les lots clients, menés comme une chaîne.',
      intro: 'Quand un client envoie vingt enregistrements par semaine, le travail consiste à appliquer le même traitement encore et encore, plus quelques exceptions. Reelfold lance d’abord un petit pilote, puis tout le lot en parallèle, et ne vous montre que ce que ses contrôles signalent.',
      img: 'typing', figCaption: 'Une demande pour trois lives : neuf clips d’environ une minute, un par jour à partir de jeudi.', figAlt: 'L’accueil de Reelfold avec une demande saisie : découper les trois lives de la semaine en clips Xiaohongshu et Douyin, avec le résumé du plan en dessous.',
      pointsT: 'Ce dont un studio a besoin',
      points: [
        { t: 'Un espace par client', b: 'Style, plateformes, glossaire, règles d’hésitations et couleurs de marque ne s’appliquent qu’aux lots de ce client.' },
        { t: 'Un pilote avant le lot', b: 'Quelques clips tournent de bout en bout d’abord, pour qu’une erreur ne se répète pas sur cent tâches.' },
        { t: 'Relecture des exceptions', b: 'Contrôles automatiques du volume, de la synchro, des mots manquants, du texte sous les boutons, de la durée et de la longueur du titre. Seuls les rouges vous parviennent.' },
        { t: 'Un paquet de livraison', b: 'Un dossier par plateforme, un calendrier, les textes de publication et un manifeste avec sommes de contrôle, prêt à remettre.' },
      ],
      stepsT: 'Une semaine pour un client',
      steps: [
        { t: 'Importez les enregistrements', b: 'Déposez un dossier. Chaque fichier est planifié avec les réglages du client.' },
        { t: 'Lancez le pilote', b: 'Vérifiez deux ou trois clips. Corrigez le plan une fois, pour toutes les tâches suivantes.' },
        { t: 'Lancez le lot', b: 'Les tâches tournent en parallèle, et un lot interrompu reprend là où il s’était arrêté.' },
        { t: 'Livrez', b: 'Relisez les quelques clips signalés, puis remettez les dossiers ou remplissez vous-même chaque page de mise en ligne.' },
      ],
      faq: [
        { q: 'Y a-t-il un tarif par poste ou à la minute ?', a: 'Non. Reelfold est gratuit et sous licence MIT. Vous ne payez que l’IA que vous branchez : le lot de 72 minutes de la page d’accueil a coûté 0,73 $.' },
        { q: 'Mon client peut-il publier lui-même ?', a: 'Oui. Le dossier de livraison contient les vidéos, couvertures, textes et un calendrier. La liste de publication lui rappelle de cocher le label IA de chaque plateforme.' },
        { q: 'Puis-je l’automatiser ?', a: 'Oui. Le moteur est open source et tourne en ligne de commande ou comme skill Claude Code.' },
      ],
      cta: 'Lancez votre prochain lot client sur votre Mac.',
      related: ['course-slicing', 'interview-clips', 'compare/capcut'],
    },
    es: {
      nav: 'Estudios y lotes',
      title: 'Edición de video por lotes para estudios y clientes | Reelfold',
      description: 'Aplica la misma edición a muchas grabaciones: primero un piloto, luego tareas en paralelo en tu Mac, revisión solo de las excepciones y una carpeta de entrega por plataforma. App gratuita y de código abierto para Mac.',
      kicker: 'Uso · Estudios',
      h1: 'Lotes de clientes, como una línea de producción.',
      intro: 'Cuando un cliente manda veinte grabaciones por semana, el trabajo es el mismo tratamiento repetido muchas veces, más unas pocas excepciones. Reelfold hace primero un pequeño piloto, luego procesa todo el lote en paralelo y solo te muestra lo que marcan sus controles.',
      img: 'typing', figCaption: 'Una petición para tres directos: nueve clips de un minuto, uno al día a partir del jueves.', figAlt: 'La pantalla de inicio de Reelfold con una petición escrita: cortar los tres directos de la semana en clips para Xiaohongshu y Douyin, con el resumen del plan debajo.',
      pointsT: 'Lo que necesita un estudio',
      points: [
        { t: 'Un espacio por cliente', b: 'Estilo, plataformas, glosario, reglas de muletillas y colores de marca se aplican solo a los lotes de ese cliente.' },
        { t: 'Piloto antes del lote', b: 'Primero se procesan unos pocos clips de principio a fin, para que un error no se repita en cien tareas.' },
        { t: 'Revisión solo de excepciones', b: 'Controles automáticos de volumen, sincronía, palabras que faltan en los subtítulos, texto bajo los botones, duración y largo del título. Solo te llega lo rojo.' },
        { t: 'Un paquete de entrega', b: 'Una carpeta por plataforma, un calendario, los textos y un manifiesto con sumas de verificación, listo para entregar.' },
      ],
      stepsT: 'Una semana para un cliente',
      steps: [
        { t: 'Importa las grabaciones', b: 'Arrastra una carpeta. Cada archivo se planifica con la configuración del cliente.' },
        { t: 'Haz el piloto', b: 'Revisa dos o tres clips. Corrige el plan una vez, para todas las tareas siguientes.' },
        { t: 'Procesa el lote', b: 'Las tareas corren en paralelo, y un lote interrumpido sigue donde se quedó.' },
        { t: 'Entrega', b: 'Revisa los pocos marcados y entrega las carpetas, o rellena tú mismo cada página de subida.' },
      ],
      faq: [
        { q: '¿Se paga por puesto o por minuto?', a: 'No. Reelfold es gratis y tiene licencia MIT. Solo pagas la IA que conectes: el lote de 72 minutos de la página de inicio costó 0,73 US$.' },
        { q: '¿Mi cliente puede publicar por su cuenta?', a: 'Sí. La carpeta de entrega trae los videos, las portadas, los textos y un calendario. La lista de publicación le recuerda marcar la etiqueta de IA de cada plataforma.' },
        { q: '¿Se puede automatizar?', a: 'Sí. El motor es de código abierto y funciona desde la línea de comandos o como skill de Claude Code.' },
      ],
      cta: 'Procesa el próximo lote de tu cliente en tu Mac.',
      related: ['course-slicing', 'interview-clips', 'compare/capcut'],
    },
  },
};

export const useCase = (slug: string, lang: Lang): UseCase => {
  const d = DATA[slug as UseCaseSlug];
  if (!d) throw new Error(`unknown use case ${slug}`);
  return d[lang];
};
