#!/usr/bin/env python3
"""Polish any exported edit (Descript, CapCut/剪映, Premiere, Resolve, Final Cut...) for publishing.

Steps (each its own ffmpeg call, intermediates kept with --keep so you can inspect any stage):
  0. cleanup  OPTIONAL (--cleanup pauses|gentle|standard|tight; default off): the shared 气口 / filler / repeat
              tool vstudio.cleanup on the export (analyze -> review sheet -> apply auto edits + --cleanup-reply
              "确认 3,5 / 保留 7"). Never re-cuts an already-cleaned file (sidecar check + cleanup.apply's
              duration guard). See references/CLEANUP.md.
  0b. studio OPTIONAL (--studio-sound light|standard|strong): denoise, dereverb, voice EQ (vstudio.studiosound),
              video stream-copied. For phone / laptop / room audio (Descript Studio Sound / 剪映 人声增强)
  0c. music  OPTIONAL (--music calm|warm|bright|tech|story|<file>): a background bed ducked under the voice
              (vstudio.music built-in beds are generated by code: free for any use)
  1. cover    replace the first N seconds of picture with a still cover (audio untouched, length kept)
  2. speed    optional pitch-preserved speed-up (setpts + atempo chain)
  3. loudness two-pass loudnorm to persona.audio.loudness_lufs (measure, then linear apply)
  4. finalize bt709 colour tags + faststart (stream copy; tags via h264/hevc_metadata bsf)

Resolution and frame rate always follow the source. Re-encodes target the source bitrate
(platforms re-encode anyway; you only lose quality by going lower).

Platforms (vstudio.platform profiles; omit --platform for the platform-neutral behaviour):
  --platform youtube                  one target: loudness / encode cap / length check / cover size from the
                                      profile, plus <out stem>.cover.jpg at the platform cover size
  --platform douyin,xiaohongshu:vertical
                                      several targets: polish the master once (-o), then vstudio.export
                                      writes one file + cover per platform and manifest.json into --out-dir

Usage:
  python3 polish.py export.mp4 -o final.mp4 [--cover cover.png] [--speed 1.2|body|hook] [--platform youtube]
  python3 polish.py export.mp4 -o final.mp4 --cleanup gentle [--cleanup-reply "确认 3,5 / 保留 7"]
"""
import sys, pathlib; sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[3] / "lib"))

import argparse
import json
import math
import os
import shutil
import tempfile

from vstudio import audio, media
from vstudio.config import persona


def run(cmd):
    print("  $ " + " ".join(str(c) for c in cmd[:6]) + (" ..." if len(cmd) > 6 else ""), flush=True)
    try:
        media.run(cmd)
    except media.FFmpegError as e:
        raise SystemExit(str(e))


def probe(path):
    """vstudio.media.probe + the two names this script uses (fps as a Fraction, vbr = video bps)."""
    info = media.probe(str(path))
    if not info["has_video"]:
        raise SystemExit(f"{path}: no video stream")
    info["fps"] = info["fps_q"] or 30
    info["vbr"] = info["vbitrate"]
    return info


def _bps(v):
    """"16M" / "800k" / 16000000 -> bps (int)."""
    v = str(v).strip()
    mul = {"k": 1e3, "m": 1e6, "g": 1e9}.get(v[-1:].lower(), 1)
    return int(float(v.rstrip("kKmMgG")) * mul)


def venc_args(info, args, prof=None):
    """Video encoder args. Without a platform profile: unchanged platform-neutral behaviour (source-bitrate
    matching, or CRF). With one (single --platform target): the same modes, capped by profile.encode -
    bitrate mode targets min(source, profile maxrate) with maxrate <= the cap; CRF mode uses --crf, else the
    profile crf, plus the profile maxrate/bufsize as a VBV cap."""
    enc = dict(prof.encode) if prof else {}
    if args.crf is not None or not info["vbr"]:
        crf = args.crf if args.crf is not None else enc.get("crf", persona().get("export", {}).get("crf", 18))
        q = ["-crf", str(crf)]
        if enc.get("maxrate"):
            q += ["-maxrate", str(_bps(enc["maxrate"])), "-bufsize", str(_bps(enc.get("bufsize") or enc["maxrate"]))]
    else:
        br = info["vbr"] if args.bitrate == "match" else (int(float(args.bitrate) * 1e6) if
                                                          args.bitrate.replace(".", "").isdigit() else _bps(args.bitrate))
        mr = int(br * 1.15)
        if enc.get("maxrate"):
            cap = _bps(enc["maxrate"])
            br, mr = min(br, cap), min(mr, cap)
        q = ["-b:v", str(br), "-maxrate", str(mr), "-bufsize", str(br * 2)]
    return ["-c:v", "libx264", "-preset", args.preset, *q, "-pix_fmt", "yuv420p", *media.BT709]


def resolve_speed(val):
    if val is None:
        return 1.0
    try:
        return float(val)
    except ValueError:
        sp = persona().get("speed", {})
        if val not in sp:
            raise SystemExit(f"--speed {val!r}: not a number and not a persona speed key ({', '.join(sp)})")
        return float(sp[val])


PAUSE_KINDS = {"pause", "breath", "lead", "tail"}


def cleaned_sidecar(path):
    """The ``<stem>.cleanup.json`` a vstudio.cleanup apply wrote next to ``path`` (None if it isn't one)."""
    side = pathlib.Path(path).with_suffix("").as_posix() + ".cleanup.json"
    if not pathlib.Path(side).exists():
        return None
    try:
        d = json.loads(pathlib.Path(side).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return side if d.get("tool") == "vstudio.cleanup" and d.get("out") else None


def step_cleanup(src, args, info):
    """Optional 气口 / filler / repeat pass with the shared tool (vstudio.cleanup) on an external export.
    EDL + review sheet next to the output (<out stem>.cleanup.json / _review.md), reused on re-runs so the
    creator's ids stay valid; apply = auto edits + --cleanup-reply. Returns the cleaned file (or src)."""
    from vstudio import cleanup as CL
    side = cleaned_sidecar(src)
    if side:
        print(f"  {src} is already a cleanup output ({side}); not cut again")
        return pathlib.Path(src)
    prof = args.cleanup
    base = "standard" if prof == "pauses" else prof
    edl_path = pathlib.Path(args.cleanup_edl or (pathlib.Path(args.out).with_suffix("").as_posix() + ".cleanup.json"))
    review = edl_path.with_name(edl_path.name.replace(".cleanup.json", "") + "_review.md")
    edl = None
    if edl_path.exists() and not args.cleanup_fresh:
        old = json.loads(edl_path.read_text(encoding="utf-8"))
        same = (abs(old["source"]["duration"] - info["duration"]) <= 0.1 and old.get("profile") == base
                and pathlib.Path(edl_path.parent, old["source"]["path"]).resolve() == pathlib.Path(src).resolve())
        if same or args.cleanup_edl:
            edl = dict(old, _path=str(edl_path.resolve()))      # apply's duration guard checks args.cleanup_edl
            print(f"  reusing {edl_path} (ids in {review.name} stay valid; --cleanup-fresh to re-analyse)")
    if edl is None:
        edl = CL.analyze(str(src), transcript=args.cleanup_transcript, profile=base, language=args.cleanup_lang,
                         out=str(edl_path), review=str(review), force=True)
    r = CL.parse_reply(args.cleanup_reply or "")
    keep = set(r["keep"])
    if prof == "pauses":                                 # 气口 only: every word edit stays
        keep |= {e["id"] for e in edl["edits"] if e["kind"] not in PAUSE_KINDS}
    res = CL.apply(edl["_path"], approve=r["approve"], keep=keep, all_confirm=r["all_confirm"], media_path=str(src))
    pend = [e["id"] for e in edl["edits"] if e["action"] == "confirm" and e["id"] not in res["applied"]
            and e["id"] not in keep]
    print(f"  cleanup ({prof}): {info['duration']:.2f}s -> {res['duration']:.2f}s, {len(res['applied'])} edits cut, "
          f"{len(pend)} to confirm {pend[:12]} -> review {review}")
    if pend:
        print(f'  to cut more: re-run with --cleanup {prof} --cleanup-reply "确认 {",".join(map(str, pend[:3]))} / 保留 N"')
    if args.cleanup_verify:
        rep = CL.verify(res["out"])
        if not rep["ok"]:
            raise SystemExit("cleanup verify failed: content words lost (see the .verify.json); keep that edit "
                             "with --cleanup-reply \"保留 N\" and re-run")
    return pathlib.Path(res["out"])


def step_cover(src, cover, out, info, args):
    w, h, fps, t = info["w"], info["h"], info["fps"], args.cover_sec
    fit = (f"scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h}" if args.cover_fit == "fill"
           else f"scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2:black")
    fc = (f"[0:v]{fit},setsar=1,fps={fps},format=yuv420p[c];"
          f"[1:v]trim=start={t},setpts=PTS-STARTPTS,scale={w}:{h},setsar=1,fps={fps},format=yuv420p[r];"
          f"[c][r]concat=n=2:v=1:a=0[v]")
    cmd = ["ffmpeg", "-y", "-loop", "1", "-t", t, "-i", cover, "-i", src,
           "-filter_complex", fc, "-map", "[v]"]
    cmd += (["-map", "1:a", "-c:a", "copy"] if info["has_audio"] else [])
    run(cmd + venc_args(info, args, args.prof) + [out])


def step_speed(src, out, s, info, args):
    fc = f"[0:v]setpts=PTS/{s}[v]" + (f";[0:a]{media.atempo_chain(s)}[a]" if info["has_audio"] else "")
    cmd = ["ffmpeg", "-y", "-i", src, "-filter_complex", fc, "-map", "[v]"]
    # keep audio lossless-ish until loudnorm; PCM in MOV avoids a lossy generation
    cmd += (["-map", "[a]", "-c:a", "pcm_s24le"] if info["has_audio"] else [])
    run(cmd + venc_args(info, args, args.prof) + [out])


def step_loudness(src, out, args, lufs):
    """Two-pass linear loudnorm (vstudio.audio.loudnorm_2pass): 48 kHz stereo AAC, video stream-copied."""
    if args.skip_if_close:
        m = audio.measure_loudness(str(src), lufs, args.tp_eff, args.lra)
        if abs(m["input_i"] - lufs) <= 1.0 and m["input_tp"] <= args.tp_eff + 0.5:
            print(f"  measured: I={m['input_i']} LUFS  TP={m['input_tp']} dBTP - within 1 LU of target; "
                  "encoding audio as AAC without gain change")
            ab = persona().get("export", {}).get("audio_bitrate", "192k")
            run(["ffmpeg", "-y", "-i", src, "-map", "0:v", "-map", "0:a", "-c:v", "copy",
                 "-af", "aresample=48000", "-c:a", "aac", "-b:a", ab, out])
            return
    m = audio.loudnorm_2pass(str(src), str(out), lufs=lufs, tp=args.tp_eff, lra=args.lra)
    print(f"  measured: I={m['input_i']} LUFS  TP={m['input_tp']} dBTP  LRA={m['input_lra']}")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("src", help="exported edit (mp4/mov)")
    p.add_argument("-o", "--out", required=True, help="final mp4")
    p.add_argument("--cover", help="cover image (any size; fitted to the source frame)")
    p.add_argument("--cover-sec", default="1.0", help="seconds of picture the cover replaces (default 1.0)")
    p.add_argument("--cover-fit", choices=["fill", "fit"], default="fill", help="crop-to-fill or letterbox")
    p.add_argument("--speed", help="number (1.2) or a persona speed key (body, hook, fast_body...). Default 1.0")
    p.add_argument("--lufs", type=float, help="target integrated loudness (default persona audio.loudness_lufs, "
                                              "or the single --platform profile's)")
    p.add_argument("--tp", type=float, help="true-peak ceiling dBTP (default -1.5, or the --platform profile's)")
    p.add_argument("--lra", type=float, default=11, help="loudness range target (default 11, spoken word)")
    p.add_argument("--no-loudnorm", action="store_true")
    p.add_argument("--skip-if-close", action="store_true", help="leave gain alone if already within 1 LU")
    p.add_argument("--bitrate", default="match", help="'match' source video bitrate, or e.g. 28M")
    p.add_argument("--crf", type=int, help="use CRF instead of bitrate targeting")
    p.add_argument("--preset", default="slow")
    p.add_argument("--keep", metavar="DIR", help="keep intermediates (01_cover.mp4, 02_speed.mov, 03_loud.mp4) here")
    p.add_argument("--check", action="store_true", help="after writing, dump first frame next to the output")
    c = p.add_argument_group("speech cleanup (vstudio.cleanup, references/CLEANUP.md) - default off")
    c.add_argument("--cleanup", choices=["pauses", "gentle", "standard", "tight"],
                   help="cut 气口 / fillers / repeats before the other steps: pauses = 气口 only, gentle / standard / "
                        "tight = the shared profiles (auto edits only, see --cleanup-reply)")
    c.add_argument("--cleanup-reply", help='creator decisions on the review sheet, e.g. "确认 3,5,9 / 保留 7"')
    c.add_argument("--cleanup-transcript", help="transcript JSON of the export (default: transcribe it)")
    c.add_argument("--cleanup-lang", help="ASR language (zh / en)")
    c.add_argument("--cleanup-edl", help="use this EDL (default <out stem>.cleanup.json, reused on re-runs)")
    c.add_argument("--cleanup-fresh", action="store_true", help="re-analyse even if the EDL exists")
    c.add_argument("--cleanup-verify", action="store_true", help="re-ASR the cut and stop if content words were lost")
    p.add_argument("--studio-sound", nargs="?", const="standard", choices=["light", "standard", "strong"],
                   help="clean the voice first: denoise, dereverb, voice EQ (default strength: standard)")
    p.add_argument("--music", help="background bed under the voice: a mood (calm / warm / bright / tech / story, "
                                   "built-in, free to use) or your own music file")
    p.add_argument("--music-db", type=float, default=-30.0, help="music bed loudness before ducking (default -30 LUFS)")
    g = p.add_argument_group("platforms (vstudio.platform)")
    g.add_argument("--platform", metavar="SPEC",
                   help="target name[:orientation] (xiaohongshu:vertical, douyin, youtube, youtube-shorts, "
                        "bilibili:horizontal...) or a comma list for multi-platform export. Default: none "
                        "(platform-neutral polish)")
    g.add_argument("--out-dir", default="exports", help="multi-target: per-platform files + manifest.json (default exports/)")
    g.add_argument("--cues", help="multi-target: cues.json or .srt burned per platform by vstudio.export "
                                  "(the master must be caption-free)")
    g.add_argument("--reframe-mode", default="face", choices=["face", "center", "pad-blur", "letterbox"],
                   help="multi-target: vstudio.export reframe mode when the aspect changes (default face)")
    args = p.parse_args()

    targets = []
    if args.platform:
        from vstudio import platform as P
        try:
            targets = P.parse_targets(args.platform)
        except KeyError as e:
            raise SystemExit(f"--platform {args.platform!r}: {e}. Known: {', '.join(P.list_profiles())}")
    multi = len(targets) > 1
    args.prof = targets[0] if len(targets) == 1 else None
    if (args.cues or args.out_dir != "exports") and not multi:
        print("  note: --out-dir/--cues only apply to a multi-target --platform list; ignored")

    try:
        media.ffmpeg_bin(); media.ffprobe_bin()
    except media.FFmpegError as e:
        raise SystemExit(str(e))
    prof = args.prof
    if args.lufs is not None:
        lufs = args.lufs
    elif prof:
        lufs = float(prof.loudness["lufs"])
    else:
        lufs = float(persona().get("audio", {}).get("loudness_lufs", -14))
    args.tp_eff = args.tp if args.tp is not None else (float(prof.loudness["tp"]) if prof else -1.5)
    speed = resolve_speed(args.speed)
    cap = float(persona().get("speed", {}).get("cjk_max_intelligible", 1.4))
    if speed > cap:
        print(f"  warning: speed {speed} > persona speed.cjk_max_intelligible {cap}; speech may become hard to follow")

    info = probe(args.src)
    print(f"source: {info['w']}x{info['h']} @ {float(info['fps']):.3f} fps, {info['vbr'] / 1e6:.1f} Mbps, "
          f"{info['duration']:.2f}s, audio={'yes' if info['has_audio'] else 'no'}")

    if prof:
        print(f"platform: {prof.key} ({prof.label}) {prof.w}x{prof.h}, {lufs} LUFS / {args.tp_eff} dBTP, "
              f"encode {prof.encode}")
        if abs(math.log((info["w"] / info["h"]) / (prof.w / prof.h))) > 0.01:
            print(f"  warning: source {info['w']}x{info['h']} is not the {prof.key} canvas {prof.w}x{prof.h} "
                  f"({prof.aspect}); this single-target path does NOT reframe. For a reframed per-platform file use "
                  f"the multi-target path (--platform {prof.key},<another>) or "
                  f"`python -m vstudio.export {args.out} --platforms {prof.key}`")
        fmax = prof.fps.get("max")
        if fmax and float(info["fps"]) > fmax + 0.5:
            print(f"  warning: source {float(info['fps']):.2f} fps > {prof.key} max {fmax} fps; the platform will "
                  "resample (vstudio.export converts to the profile default)")
    if multi:
        print(f"multi-platform: {', '.join(t.key for t in targets)} -> {args.out_dir}/ "
              f"(master polished at {lufs} LUFS first)")

    work = pathlib.Path(args.keep) if args.keep else pathlib.Path(tempfile.mkdtemp(prefix="polish_"))
    work.mkdir(parents=True, exist_ok=True)
    cur = pathlib.Path(args.src)
    try:
        if args.cleanup:
            if not info["has_audio"]:
                print("  --cleanup: the export has no audio; skipped")
            else:
                print(f">>> 0/4 cleanup ({args.cleanup})")
                cur = step_cleanup(cur, args, info)
                if cur != pathlib.Path(args.src):     # same canvas / fps / bitrate target, shorter
                    info = dict(info, duration=probe(cur)["duration"])
        if args.studio_sound and info["has_audio"]:
            from vstudio import studiosound
            print(f">>> 0b/4 studio sound ({args.studio_sound})")
            nxt = work / "00_studio.mp4"
            rep = studiosound.enhance(str(cur), str(nxt), args.studio_sound, lufs=False)
            print(f"  noise {rep['before']['noise_db']} -> {rep['after']['noise_db']} dB")
            cur = nxt
        if args.music and info["has_audio"]:
            from vstudio import music as MU
            bed = MU.resolve(args.music, duration=float(probe(cur)["duration"]))
            print(f">>> 0c/4 music bed ({os.path.basename(bed)})")
            wav, nxt = work / "00_mix.wav", work / "00_music.mp4"
            audio.mix_bed(str(cur), bed, str(wav), music_lufs=args.music_db)
            audio._encode_audio(str(cur), str(wav), str(nxt))
            cur = nxt
        if args.cover:
            print(">>> 1/4 cover")
            nxt = work / "01_cover.mp4"; step_cover(cur, args.cover, nxt, info, args); cur = nxt
        if abs(speed - 1.0) > 1e-6:
            print(f">>> 2/4 speed x{speed}")
            nxt = work / "02_speed.mov"; step_speed(cur, nxt, speed, info, args); cur = nxt
        if info["has_audio"] and not args.no_loudnorm:
            print(f">>> 3/4 loudnorm -> {lufs} LUFS (two-pass)")
            nxt = work / "03_loud.mp4"; step_loudness(cur, nxt, args, lufs); cur = nxt
        print(">>> 4/4 bt709 tags + faststart")
        media.retag_bt709(str(cur), str(args.out))
    finally:
        if not args.keep:
            shutil.rmtree(work, ignore_errors=True)

    fin = probe(args.out)
    print(f"\ndone: {args.out}\n  {fin['w']}x{fin['h']} @ {float(fin['fps']):.3f} fps, {fin['vbr'] / 1e6:.1f} Mbps, "
          f"{fin['duration']:.2f}s (expected ~{info['duration'] / speed:.2f}s)")
    if fin["has_audio"]:
        m = audio.measure_loudness(str(args.out), lufs, args.tp_eff, args.lra)
        print(f"  loudness: I={m['input_i']} LUFS  TP={m['input_tp']} dBTP")
    if args.check:
        png = pathlib.Path(args.out).with_suffix(".first.png")
        media.grab_frame(str(args.out), 0.3, str(png))
        print(f"  first frame: {png}")
    if prof:
        platform_single(prof, args, fin)
    elif multi:
        platform_multi(targets, args)


def platform_single(prof, args, fin):
    """Length check + platform-sized cover (<out stem>.cover.jpg) for one --platform target."""
    from vstudio import export as X
    from vstudio import platform as P
    for w in P.check_length(prof, fin["duration"]):
        print(f"  warning: {w}")
    cover = str(pathlib.Path(args.out).with_suffix("")) + ".cover.jpg"
    path, notes = X.make_cover(prof, [args.cover] if args.cover else None, str(args.out), cover)
    cw, ch = P.cover_size(prof)
    print(f"  cover: {path} ({cw}x{ch}, {prof.key})")
    for n in notes:
        print(f"    note: {n}")


def platform_multi(targets, args):
    """Hand the polished master to vstudio.export: one file + cover per platform and manifest.json."""
    from vstudio import export as X
    print(f"\n>>> export {len(targets)} targets -> {args.out_dir}/")
    man = X.export(str(args.out), targets, args.out_dir, cues=args.cues,
                   covers=[args.cover] if args.cover else None, mode=args.reframe_mode, preset=args.preset)
    for e in man["exports"]:
        print(f"  {e['file']:32s} {e['w']}x{e['h']} {e['duration']:.1f}s "
              f"{(e['loudness'] or {}).get('i', '-')} LUFS  cover={e['cover']}  reframe={e['reframe']['mode_used']}")
    for w in man["warnings"]:
        print(f"  warning: {w}")
    print(f"  manifest: {pathlib.Path(args.out_dir) / 'manifest.json'}")


if __name__ == "__main__":
    main()
