#!/usr/bin/env python3
"""Generate the Reference pages of the docs from the engine's own sources, so they never drift.

    python3 apps/docs/scripts/gen_reference.py          (or: npm run gen -w apps/docs)

Writes (English; other locales fall back to these):
  src/content/docs/reference/workflows/<name>.md   <- workflows/<name>/WORKFLOW.md
  src/content/docs/reference/engine/<slug>.md      <- references/<NAME>.md (long-form engine notes)
  src/content/docs/reference/effects.md            <- references/EFFECTS.md (itself generated from lib/vstudio/effects.py)
  src/content/docs/reference/captions.md           <- references/CAPTION_RULES.md
  src/content/docs/reference/messages.md           <- references/MESSAGES.md (itself generated from messages.py)
  src/content/docs/reference/platforms.md          <- lib/vstudio/platform.py (live profiles) + references/PLATFORMS.md
  src/content/docs/reference/persona.md            <- persona.example.yaml
  src/content/docs/reference/cli.md                <- `python -m vstudio.<module> --help`

Every generated file starts with a "generated" comment; edit the source, then re-run this script.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
REPO = DOCS.parents[1]
OUT = DOCS / "src" / "content" / "docs" / "reference"
GH = "https://github.com/zyziyun/reelfold/blob/main/"
sys.path.insert(0, str(REPO / "lib"))

WORKFLOWS = {  # name -> (sidebar order, short description)
    "talkinghead": (1, "Talking-head (口播) recording into a tight captioned short."),
    "longform-to-short": (2, "Long recording into a course cut and/or N short episodes or vertical slices."),
    "call-clips": (3, "Calls, interviews and podcasts into clips, with optional face masking."),
    "promo-recut": (4, "Talking head plus screenshots or another video into a premium promo."),
    "photo-story": (5, "Photos and a narration script (or music) into an effect-rich story."),
    "vlog": (6, "B-roll into a calm or fast, beat-cut vlog."),
    "explainer": (7, "A topic into a 3Blue1Brown-style animated explainer."),
    "polish": (8, "Any exported edit made publish-ready: cover frame, loudness, speed, cleanup."),
    "cover": (9, "Covers and thumbnails for each platform size."),
    "slides": (10, "Square or full-canvas slides for vertical videos."),
    "preproduction": (11, "Script writing, per-platform script lint and pronunciation drills."),
    "ai-video": (12, "AI-generated video (Kling, Seedance, MiniMax) with a credit budget."),
    "batch": (13, "Many shorts at once: plan, pilot, parallel runs, QC, review, packages."),
}

ENGINE = {  # references file -> (slug, order)
    "INTAKE.md": ("intake", 1),
    "PROJECTS.md": ("projects", 2),
    "BATCH.md": ("batch", 3),
    "CLEANUP.md": ("cleanup", 4),
    "OUTPUT_EDIT.md": ("output-edit", 5),
    "PROVIDERS.md": ("providers", 6),
    "PUBLISHING.md": ("publishing", 7),
    "STYLE_RULES.md": ("style-rules", 8),
    "AESTHETICS.md": ("aesthetics", 9),
    "SOUND.md": ("sound", 10),
    "RETOUCH.md": ("retouch", 11),
    "SOP_SHORT_VIDEO.md": ("sop-short-video", 12),
    "ADDING_EFFECTS.md": ("adding-effects", 13),
    "VALIDATION.md": ("validation", 14),
}
TOP = {"EFFECTS.md": "effects", "CAPTION_RULES.md": "captions", "MESSAGES.md": "messages", "PLATFORMS.md": "platforms"}

# Repo file -> docs route (for rewriting links between generated pages).
ROUTES = {f"references/{k}": f"/docs/reference/engine/{v[0]}/" for k, v in ENGINE.items()}
ROUTES.update({f"references/{k}": f"/docs/reference/{v}/" for k, v in TOP.items()})
ROUTES.update({f"workflows/{k}/WORKFLOW.md": f"/docs/reference/workflows/{k}/" for k in WORKFLOWS})
ROUTES["persona.example.yaml"] = "/docs/reference/persona/"

STAMP = "<!-- Generated by apps/docs/scripts/gen_reference.py from {src}. Do not edit here: edit the source and re-run. -->"


def yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def front(title: str, description: str, order: int | None = None, extra: str = "") -> str:
    fm = ["---", f"title: {yaml_str(title)}", f"description: {yaml_str(description)}"]
    if order is not None:
        fm.append(f"sidebar:\n  order: {order}")
    fm.append("editUrl: false")
    if extra:
        fm.append(extra)
    fm.append("---")
    return "\n".join(fm) + "\n"


def split_title(md: str) -> tuple[str, str]:
    lines = md.splitlines()
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return line[2:].strip(), "\n".join(lines[:i] + lines[i + 1:]).lstrip("\n")
    return "", md


def first_paragraph(md: str, limit: int = 158) -> str:
    in_code = False
    for block in re.split(r"\n\s*\n", md):
        b = block.strip()
        if b.startswith("```"):
            in_code = not in_code if b.count("```") % 2 else in_code
            continue
        if in_code or not b or b[0] in "#|>-<*!" or b.startswith("    "):
            continue
        text = re.sub(r"\s+", " ", b)
        text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
        text = text.replace("**", "").replace("`", "")
        if len(text) > limit:
            text = text[: limit - 1].rsplit(" ", 1)[0].rstrip(",;:") + "…"
        return text
    return ""


def rewrite_links(md: str, src: Path) -> str:
    base = src.parent

    def fix(m: re.Match) -> str:
        text, target = m.group(1), m.group(2)
        if re.match(r"^[a-z]+:|^#|^/", target):
            return m.group(0)
        path, _, anchor = target.partition("#")
        resolved = os.path.normpath(os.path.join(base.relative_to(REPO), path)).replace(os.sep, "/")
        if resolved in ROUTES:
            url = ROUTES[resolved] + (f"#{anchor.lower()}" if anchor else "")
        else:
            url = GH + resolved + (f"#{anchor}" if anchor else "")
        return f"[{text}]({url})"

    out, in_code = [], False
    for line in md.splitlines():
        if line.lstrip().startswith("```"):
            in_code = not in_code
        out.append(line if in_code else re.sub(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)\)", fix, line))
    md = "\n".join(out)
    # Images: point at GitHub raw so they render without copying assets.
    md = re.sub(r"!\[([^\]]*)\]\((?!https?:)([^)]+)\)",
                lambda m: f"![{m.group(1)}](https://raw.githubusercontent.com/zyziyun/reelfold/main/"
                f"{os.path.normpath(os.path.join(src.parent.relative_to(REPO), m.group(2)))})", md)
    return md


def demote(md: str) -> str:
    """Generated bodies keep their own heading levels (## and below); a stray `# ` becomes `##`."""
    out, in_code = [], False
    for line in md.splitlines():
        if line.lstrip().startswith("```"):
            in_code = not in_code
        out.append("#" + line if (not in_code and line.startswith("# ")) else line)
    return "\n".join(out)


def source_note(rel: str) -> str:
    return (f":::note[Source]\nThis page is generated from [`{rel}`]({GH}{rel}) in the repository, "
            "the same file the engine and the Claude Code skill read.\n:::\n\n")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    print("wrote", path.relative_to(DOCS))


def gen_workflows() -> None:
    for name, (order, desc) in WORKFLOWS.items():
        src = REPO / "workflows" / name / "WORKFLOW.md"
        rel = src.relative_to(REPO).as_posix()
        h1, body = split_title(src.read_text(encoding="utf-8"))
        subtitle = re.split(r"\s+[—:-]\s+", h1, maxsplit=1)
        title = f"{name}" + (f": {subtitle[1]}" if len(subtitle) > 1 else "")
        body = demote(rewrite_links(body, src))
        fm = (f"---\ntitle: {yaml_str(title)}\ndescription: {yaml_str(desc)}\n"
              f"sidebar:\n  label: {yaml_str(name)}\n  order: {order}\neditUrl: false\n---\n")
        write(OUT / "workflows" / f"{name}.md", fm
              + STAMP.format(src=rel) + "\n\n" + source_note(rel) + body)


def gen_engine() -> None:
    for fname, (slug, order) in ENGINE.items():
        src = REPO / "references" / fname
        rel = src.relative_to(REPO).as_posix()
        h1, body = split_title(src.read_text(encoding="utf-8"))
        desc = first_paragraph(body) or h1
        write(OUT / "engine" / f"{slug}.md",
              front(h1, desc, order) + STAMP.format(src=rel) + "\n\n" + source_note(rel) + demote(rewrite_links(body, src)))


def gen_top(fname: str, slug: str, title: str, desc: str, intro: str = "") -> None:
    src = REPO / "references" / fname
    rel = src.relative_to(REPO).as_posix()
    _, body = split_title(src.read_text(encoding="utf-8"))
    write(OUT / f"{slug}.md",
          front(title, desc) + STAMP.format(src=rel) + "\n\n" + source_note(rel) + intro + demote(rewrite_links(body, src)))


def gen_platforms() -> None:
    from vstudio import platform as P

    rows_by_group = []
    for group, names in P.GROUPS.items():
        rows = []
        for name in names:
            keys = [k for k in P.list_profiles() if k.split(":")[0] == name]
            for k in keys:
                pr = P.profile(*k.split(":"), use_persona=False)
                ln = pr.length or {}
                sweet = ln.get("sweet") or ["", ""]
                title = "none" if not pr.title_max else f"{pr.title_max:g}"
                cov = pr.cover or {}
                rows.append(
                    f"| `{k}` | {pr.label} | {pr.w}×{pr.h} ({pr.aspect}) | {cov.get('w')}×{cov.get('h')} | "
                    f"{sweet[0]}–{sweet[1]} s / max {fmt_s(ln.get('max'))} | {title} | "
                    f"{pr.loudness.get('lufs'):g} LUFS / {pr.loudness.get('tp'):g} dBTP |")
        rows_by_group.append((P.GROUP_LABELS[group]["en"], rows))

    pub = ["| Platform | Upload page (assisted) | Official API (opt-in only) |", "|---|---|---|"]
    for name in P.ORDER:
        d = P.PUBLISHING.get(name, {})
        up = d.get("upload_url")
        pub.append(f"| `{name}` | {f'<{up}>' if up else d.get('note', '—')} | {d.get('api') or '—'} |")

    src = REPO / "references" / "PLATFORMS.md"
    _, prose = split_title(src.read_text(encoding="utf-8"))
    parts = [front("Platform specs", "Every platform profile Reelfold exports to: canvas, cover, length, title limit "
                   "and loudness, generated from the engine's own profiles."),
             STAMP.format(src="lib/vstudio/platform.py + references/PLATFORMS.md"), "",
             source_note("lib/vstudio/platform.py"),
             "One clean master becomes one file per platform below. Pick targets with `--platforms` "
             "(`python -m vstudio.export master.mp4 --platforms xiaohongshu:vertical,douyin,youtube-shorts`), in a "
             "batch spec, or in the app's export step. Print the live table on your machine with "
             "`cd lib && python3 -m vstudio.platform`; override any value per creator in `persona.local.yaml` "
             "under `platforms.<name>`.\n"]
    head = "| Profile | Platform | Canvas | Cover | Length (sweet spot / max) | Title max | Loudness |\n|---|---|---|---|---|---|---|"
    for label, rows in rows_by_group:
        parts.append(f"## {label}\n\n{head}\n" + "\n".join(rows) + "\n")
    parts.append("## How each platform is published\n\nPublishing is assisted by default: the app opens the "
                 "platform's own upload page, fills in the file and the copy, and you press publish. An API uploader "
                 "is only used when you configure one and confirm each post. See [Assisted publishing]"
                 "(/docs/concepts/publishing/).\n\n" + "\n".join(pub) + "\n")
    parts.append("## Notes and sources\n\n" + demote(demote(rewrite_links(prose, src)).replace("\n## ", "\n### ")))
    write(OUT / "platforms.md", "\n".join(parts))


def fmt_s(s) -> str:
    if not s:
        return "—"
    s = int(s)
    if s >= 3600:
        return f"{s / 3600:g} h"
    if s >= 60:
        return f"{s // 60} min" + (f" {s % 60} s" if s % 60 else "")
    return f"{s} s"


PERSONA_SECTIONS = {
    "creator": "Your name and handle (covers, end cards) and the language you speak in your videos.",
    "platforms": "Default platform and per-platform overrides deep-merged over the built-in profiles.",
    "speed": "Playback rates used when you just say \"speed it up\" (hook, body, B-roll).",
    "audio": "Delivery loudness, narration and music levels, pause squeezing.",
    "export": "Frame rate, quality, audio bitrate, colour tags and the H.264 encoder.",
    "style": "The design theme every overlay, card and caption uses.",
    "brand": "Your ink and ground colours.",
    "fonts": "Your own font files per role (cjk, cjk-bold, cjk-serif, serif, mono…), including one face of a .ttc.",
    "subtitles": "Caption line length, keyword highlight markup and ASR term fixes.",
    "voice": "Voice rules for scripts and post copy.",
    "publish": "Default hashtags, named tag sets and the chapter line format.",
    "intake": "How the planner treats materials (for example burned-in captions).",
    "cleanup": "Default cleanup profile, crossfade, extra fillers and words never to cut.",
}


def gen_persona() -> None:
    src = REPO / "persona.example.yaml"
    text = src.read_text(encoding="utf-8")
    # Top-level sections and the comment right after the key (if any).
    sections, cur = [], None
    for line in text.splitlines():
        m = re.match(r"^([a-z_]+):(.*)$", line)
        if m:
            cur = [m.group(1), m.group(2).partition("#")[2].strip(), []]
            sections.append(cur)
        elif cur and re.match(r"^  [a-z_]+:", line):
            key = line.split(":")[0].strip()
            if key not in cur[2]:
                cur[2].append(key)
    rows = ["| Section | What it sets | Keys |", "|---|---|---|"]
    for name, comment, keys in sections:
        ks = ", ".join(f"`{k}`" for k in keys[:12]) + (" …" if len(keys) > 12 else "")
        what = PERSONA_SECTIONS.get(name) or comment.replace('|', '/') or '—'
        rows.append(f"| [`{name}`](#{name}) | {what} | {ks} |")
    blocks = []
    lines = text.splitlines()
    idx = [i for i, l in enumerate(lines) if re.match(r"^[a-z_]+:", l)] + [len(lines)]
    for a, b in zip(idx, idx[1:]):
        name = lines[a].split(":")[0]
        # Include comment lines that sit just above a section with it.
        chunk = "\n".join(lines[a:b]).rstrip()
        while chunk.endswith("\n") or (chunk.splitlines() and chunk.splitlines()[-1].startswith("#")):
            chunk = "\n".join(chunk.splitlines()[:-1]).rstrip()
        blocks.append(f"### `{name}`\n\n```yaml\n{chunk}\n```\n")
    header = " ".join(l[1:].strip() for l in lines[: idx[0]] if l.startswith("#"))
    body = (front("persona.yaml options", "Every option in persona.local.yaml: speeds, loudness, brand colours and "
                  "theme, platform overrides, tags, voice rules, term fixes, fonts and AI routing.")
            + STAMP.format(src="persona.example.yaml") + "\n\n" + source_note("persona.example.yaml")
            + "Everything that is taste rather than technique lives in one file. Copy the example and edit it:\n\n"
            "```bash\ncp persona.example.yaml persona.local.yaml   # in the skill folder; git-ignored\n```\n\n"
            "The Mac app keeps the same settings under **Settings**; the skill reads `persona.local.yaml`. "
            "Any key you leave out keeps the default shown here.\n\n"
            + (f"> {header}\n\n" if header else "")
            + "## Sections\n\n" + "\n".join(rows) + "\n\n## Full example, section by section\n\n" + "\n".join(blocks))
    write(OUT / "persona.md", body)


CLI = [
    ("intake", "Say what you want and point at files: inventory, plan, revise, apply."),
    ("project", "Every workflow as a recipe; projects, runs, checkpoints, inbox, outputs, calendar."),
    ("batch", "Batch production: plan, estimate, run, status, review, package."),
    ("cleanup", "Shared speech cleanup: pauses, fillers, repeats, restarts."),
    ("export", "One clean master into a file, cover and post stub per platform."),
    ("reframe", "Face-tracked reframe between aspect ratios."),
    ("platform", "Print the platform profiles."),
    ("effects", "List and inspect the effect registry."),
    ("llm", "AI providers on this machine: list, route, auth, test."),
    ("retouch", "Portrait retouch and makeup for photos and frames."),
]


def gen_cli() -> None:
    env = dict(os.environ, PYTHONPATH=str(REPO / "lib"), COLUMNS="100", NO_COLOR="1")
    parts = [front("CLI", "Command-line reference for the Reelfold engine (python -m vstudio.*): intake, project, "
                   "batch, cleanup, export, reframe, platform, effects, llm, retouch."),
             STAMP.format(src="`python -m vstudio.<module> --help`"), "",
             "The engine is a Python package (`vstudio`, in `lib/`). The Mac app and the Claude Code skill both call "
             "these commands; you can run them yourself from a terminal:\n\n```bash\n"
             "cd ~/.claude/skills/video-studio        # or your clone of the repository\n"
             "export PYTHONPATH=\"$PWD/lib:$PYTHONPATH\"\npython3 -m vstudio.intake --help\n```\n\n"
             "Every command that reports something accepts `--json` for one machine-readable document. "
             "Each workflow also has its own scripts under `workflows/<name>/scripts`; see "
             "[Workflows](/docs/reference/workflows/talkinghead/).\n\n| Command | What it does |\n|---|---|"]
    parts += [f"| [`vstudio.{m}`](#vstudio{m}) | {d} |" for m, d in CLI]
    parts.append("")
    for mod, desc in CLI:
        args = ["--help"] if mod != "platform" else []
        try:
            res = subprocess.run([sys.executable, "-m", f"vstudio.{mod}", *args], cwd=REPO / "lib", env=env,
                                 capture_output=True, text=True, timeout=120)
            out = (res.stdout or res.stderr).rstrip()
        except Exception as e:  # pragma: no cover
            out = f"(could not run: {e})"
        out = re.sub(r"^usage: retouch\.py", "usage: python -m vstudio.retouch", out)
        out = out.replace(str(REPO), "<repo>").replace(str(Path.home()), "~")
        parts.append(f"## `vstudio.{mod}`\n\n{desc}\n\n```text\n{out}\n```\n")
    write(OUT / "cli.md", "\n".join(parts))


def main() -> None:
    gen_workflows()
    gen_engine()
    gen_top("EFFECTS.md", "effects", "Effects and themes",
            "The effect catalogue: every visual and audio effect, which engines render it, and the design themes "
            "that style them.",
            "Effects are styled by the active design theme (`editorial` by default; also `mono`, `soft`, `night`, "
            "`xhs-pop`); see [Themes and looks](/docs/concepts/themes/) and the "
            "[style rules](/docs/reference/engine/style-rules/). Browse on your machine with "
            "`python3 -m vstudio.effects --list` or `--show <id>`.\n\n")
    gen_top("CAPTION_RULES.md", "captions", "Caption rules",
            "Rules for captions, cards and post copy: verify names after ASR, one source of truth per project, "
            "line length, emphasis and contrast.")
    gen_top("MESSAGES.md", "messages", "Messages and error codes",
            "Every engine message code with its English, Chinese and French text, and where each code appears.")
    gen_platforms()
    gen_persona()
    gen_cli()


if __name__ == "__main__":
    main()
