// First-run asset downloads (fonts, MediaPipe models, Whisper weights, optional Chromium): manifest + status types.
// The manifest is packaging/assets.json (generated by scripts/runtime/assets-lock.mjs); every file is sha256-pinned.

export interface AssetFile {
  url: string;
  /** path relative to the group root ("." allowed as first segment) */
  dest: string;
  sha256: string;
  size: number;
}

export interface AssetGroup {
  id: string;
  required: boolean;
  /** "<platform>-<arch>" targets this group applies to; all when absent */
  targets?: string[];
  /** folder under the app's asset dir */
  root: string;
  /** unzip each file into the root after verifying it */
  extract?: boolean;
  /** env vars for the engine once installed: '' = the root folder, else a path relative to the root */
  env?: Record<string, string>;
  licence: string;
  files: AssetFile[];
}

export interface AssetManifest {
  groups: AssetGroup[];
}

export interface AssetGroupStatus {
  id: string;
  required: boolean;
  installed: boolean;
  bytes: number;
  licence: string;
  /** set while this group is downloading */
  progress?: { received: number; total: number; file: string };
  error?: string;
}

export interface AssetsStatusMsg {
  dir: string;
  groups: AssetGroupStatus[];
  busy: boolean;
  /** installed since the engine started: restart the engine to use them */
  restartNeeded: boolean;
}

export function groupsFor(manifest: AssetManifest, target: string): AssetGroup[] {
  return manifest.groups.filter((g) => !g.targets || g.targets.includes(target));
}

/** Reject anything that could escape the group root (manifest is ours, but keep the writer honest). */
export function safeRel(p: string): string {
  const parts = p.split('/').filter((x) => x && x !== '.');
  if (!parts.length || parts.some((x) => x === '..' || x.includes('\\') || x.includes(':'))) throw new Error(`bad asset path ${p}`);
  return parts.join('/');
}
