#!/usr/bin/env python3
"""Subset Noto Serif SC 600 (SIL OFL, from @fontsource/noto-serif-sc) to the glyphs the 中文 headings use.

Reads the built 中文 pages (dist/zh/**/*.html), collects the CJK characters inside serif elements (h1, h2, h3,
summary, dd, b, th, the platform list) and writes two woff2 files + their @font-face rules:
  public/fonts/noto-serif-sc-600-core.woff2   characters on /zh/ (preloaded on 中文 pages)
  public/fonts/noto-serif-sc-600-extra.woff2  characters used only on other 中文 pages (unicode-range: loaded on demand)
  src/styles/zh-font.css, src/data/zh-font.json
Run after changing Chinese headings:  npm run build && python3 scripts/subset-zh-font.py && npm run build
(`npm run check:font` fails the build check when a heading character is missing from the subset.)
Needs fontTools + brotli (pip install fonttools brotli)."""
import json, pathlib, re, tempfile
from html.parser import HTMLParser
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.merge import Merger

SITE = pathlib.Path(__file__).resolve().parents[1]
NM = SITE.parents[1] / "node_modules/@fontsource/noto-serif-sc"
WEIGHT = 600
CJK = re.compile(r"[　-〿㐀-䶿一-鿿＀-￯—‘’“”·]")
SERIF_TAGS = {"h1", "h2", "h3", "summary", "dd", "b", "th"}


class Grab(HTMLParser):
    def __init__(self):
        super().__init__(); self.depth = 0; self.stack = []; self.chars = set()
    def handle_starttag(self, tag, attrs):
        cls = dict(attrs).get("class") or ""
        serif = tag in SERIF_TAGS or "plats" in cls.split()
        self.stack.append((tag, serif))
        if serif: self.depth += 1
    def handle_endtag(self, tag):
        while self.stack:
            t, serif = self.stack.pop()
            if serif: self.depth -= 1
            if t == tag: break
    def handle_data(self, data):
        if self.depth > 0: self.chars.update(CJK.findall(data))


def chars_of(path):
    g = Grab(); g.feed(path.read_text(encoding="utf-8")); return g.chars


def chunks():
    css = (NM / f"{WEIGHT}.css").read_text()
    out = []
    for m in re.finditer(r"url\(\./files/([^)]+?\.woff2)\).*?unicode-range:\s*([^;]+);", css, re.S):
        rng = []
        for part in m.group(2).split(","):
            a, _, b = part.strip()[2:].partition("-")
            rng.append((int(a, 16), int(b or a, 16)))
        out.append((NM / "files" / m.group(1), rng))
    return out


def build(chars, name):
    cps = sorted(ord(c) for c in chars)
    parts, tmp = [], pathlib.Path(tempfile.mkdtemp())
    for f, rng in chunks():
        want = [c for c in cps if any(a <= c <= b for a, b in rng)]
        if not want: continue
        font = TTFont(f)
        opts = subset.Options(); opts.layout_features = ["*"]; opts.notdef_outline = True; opts.name_IDs = ["*"]
        s = subset.Subsetter(opts); s.populate(unicodes=want); s.subset(font)
        font.flavor = None
        p = tmp / f"{len(parts)}.ttf"; font.save(p); parts.append(str(p))
    if not parts: raise SystemExit("no glyphs found")
    merged = Merger().merge(parts) if len(parts) > 1 else TTFont(parts[0])
    merged.flavor = "woff2"
    dest = SITE / "public/fonts" / name
    merged.save(dest)
    have = set(merged.getBestCmap())
    missing = [chr(c) for c in cps if c not in have]
    return dest.stat().st_size, missing


def urange(chars):
    return ", ".join(f"U+{ord(c):04X}" for c in sorted(chars))


def main():
    pages = sorted((SITE / "dist/zh").rglob("*.html"))
    if not pages: raise SystemExit("run `npm run build` first")
    core = chars_of(SITE / "dist/zh/index.html")
    everything = set().union(*(chars_of(p) for p in pages))
    extra = everything - core
    files = {"core": "noto-serif-sc-600-core.woff2", "extra": "noto-serif-sc-600-extra.woff2"}
    css = ["/* generated by scripts/subset-zh-font.py: Noto Serif SC 600 (SIL OFL 1.1), subset to the 中文 headings */"]
    for key, cs in (("core", core), ("extra", extra)):
        if not cs: continue
        size, missing = build(cs, files[key])
        print(f"{files[key]}: {len(cs)} chars, {size/1024:.1f} KB" + (f", missing {''.join(missing)}" if missing else ""))
        css.append("@font-face{font-family:'Noto Serif SC';font-style:normal;font-weight:600;font-display:swap;"
                   f"src:url(/fonts/{files[key]}) format('woff2');unicode-range:{urange(cs)}}}")
    (SITE / "src/styles/zh-font.css").write_text("\n".join(css) + "\n")
    (SITE / "src/data/zh-font.json").write_text(json.dumps(dict(core=files["core"], extra=files["extra"],
        coreChars="".join(sorted(core)), extraChars="".join(sorted(extra))), ensure_ascii=False, indent=1) + "\n")


if __name__ == "__main__":
    main()
