#!/usr/bin/env python3
"""Regenerate references/MESSAGES.md from vstudio.messages (CATALOG + FR).

    python3 scripts/gen_messages_md.py          # write the file
    python3 scripts/gen_messages_md.py --check  # exit 1 when the file is out of date (tests/test_messages.py)
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "lib"))

from vstudio import messages as M  # noqa: E402

FR = M.FR

HEAD = """# Engine messages: codes for the desk

Generated by `python3 scripts/gen_messages_md.py` from `lib/vstudio/messages.py` (do not edit by hand;
`tests/test_messages.py` fails when this file is out of date).

Every engine text a person reads comes with a stable **code** and **params**, next to the English `message` and
Chinese `message_zh` the CLI and older desks show:

    {"code": "qc.loudness", "params": {"value": -9.1, "lufs": -14, ...}, "message": "...", "message_zh": "..."}

The desk maps `code` to its own copy (en / zh-CN / fr below; `{name}` = a param) and falls back to `message` /
`message_zh` for a code it does not know. Codes whose text is `{text}` carry engine or model text through as is
(`params.text`): show it, do not translate it.

## Where the codes are

| Output | Field |
|---|---|
| `vstudio.llm` errors (`--json` of plan-segments, output ai, project ai) | `code`, `tried`, `errors`, `codes`, `attempts`, `message` (`llm-all-failed`) |
| `llm auth status` rows | `message` (`auth-*`, `key-*`, `local-*`; see `vstudio.llm_auth.MSG`) |
| plan-segments | `notices[]` (`plan-*`), `fallback` |
| intake plan | `risks_info[]`, `warnings_info[]`, `questions[].message`, `projects[].checkpoints[].label_info`, `projects[].recipe_info`, `planner.message`, `summary_info` |
| inbox entries | `label_info` (`checkpoint.<kind>`), `reason` (`inbox.<kind>`) |
| project status | `state_info` (`project-state.*`), `items[].state_info` (`job-state.*`), `items[].qc_info` (`qc-state.*`), `items[].stages[].label_info` (`stage.*`) |
| QC (`qc.json`, job detail) | `checks[].message`, `reasons_info[]`, `warnings_info[]` (`qc.<check>`) |
| `.vstudio/status.json` | `status_info` (`status.*`), `stage_info` (`stage.*`), `message_info` (`status-text` or the writer's `message_code`) |
| publishing calendar | `posts[].state_info`, `states` (`post-state.*`) |
| output ai / project ai | `summary_info`, `groups[].summary_info`, `groups[].proposed[].why_info` (`ai-summary`, `ai-why`); errors and notes already carry `code` + `params` (`vstudio.project.outputs.msg`) |
| recipes (`vstudio.project recipes --json`, project show) | `messages.label`, `messages.description` (`recipe.<id>.label`, `recipe.<id>.description`: the manifest's own zh / en texts) |

## Codes
"""


def render():
    rows = ["| Code | en | zh-CN | fr |", "|---|---|---|---|"]
    esc = lambda t: str(t).replace("|", "\\|")  # noqa: E731
    for code, (en, zh) in M.CATALOG.items():
        rows.append(f"| `{code}` | {esc(en)} | {esc(zh)} | {esc(FR.get(code, en if en == '{text}' else ''))} |")
    fam = "\n".join(f"- `{f}`" for f in M.FAMILIES)
    return HEAD + "\n" + "\n".join(rows) + "\n\nCode families with an id (texts come from the recipe manifest):\n\n" + \
        fam + "\n"


def main(argv):
    out = ROOT / "references" / "MESSAGES.md"
    txt = render()
    if "--check" in argv:
        missing = [c for c, (en, _) in M.CATALOG.items() if en != "{text}" and c not in FR]
        if missing:
            print("no French for: " + ", ".join(missing))
            return 1
        if not out.exists() or out.read_text(encoding="utf-8") != txt:
            print("references/MESSAGES.md is out of date: python3 scripts/gen_messages_md.py")
            return 1
        return 0
    out.write_text(txt, encoding="utf-8")
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
